In [ ]:
pip install pandas

In [ ]:
import pandas as pd
df=pd.read_excel('/content/banking_uncleaned_FULL_5000rows.xlsx')
df

,Account_ID,Account_Number,Name,Account_Type,Balance,Fixed_Deposit,Recurring_Deposit,Loan_Amount,Interest_Rate,Branch,City,Country,Email,Phone_Number,Transaction_Type,Withdrawal,Deposit,Transaction_Date,Account_Open_Date,Notes
0,ACC100000,9839401802,Divya,fixd depo,1642743.0,60263,16023,100268.0,10,Delhi,Mumbai,UAE,divya@gmail.com,NaN,Crdit,157892,4886,17/07/2024,24/10/2022,Remove
1,ACC100001,7548779029,Aisha,currnt,NaN,25658,18942,781743.0,12,Hyderabad,New York,United States,aisha@gmail.com,2.638243e+09,DEBIT,53355,185796,01-09-21,23.08.2016,Remove
2,ACC100002,1991681409,Aisha,currnt,3335659.0,48555,17159,NaN,16,chnnai,NaN,NaN,Aisha@@gmail.com,3.173156e+09,DEBIT,155041,124073,NaN,15-09-21,NaN
3,ACC100003,9970006983,Robert,savngs,2249435.0,89789,24276,186769.0,14,chnnai,NaN,Unites States,robert@gmail.com,4.798809e+09,DBT,-12935,173165,2022-05-19,04-02-19,NaN
4,ACC100004,9907953924,Kumar,NaN,1702126.0,52251,22662,126330.0,16,Delhi,New York,Unites States,Kumar@@gmail.com,6.674275e+08,debit,168610,-10496,2019/01/25,14.05.2022,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,ACC104995,1905811747,Divya,RD,4254142.0,26651,4944,556284.0,16,Chennai,Dubai,India,divya@gmail.com,1.322206e+09,CREDIT,176191,103276,16-06-23,26.10.2023,Temp
4996,ACC104996,3314293638,Robert,curent,NaN,42556,8389,224232.0,12,Delhi,Dubai,UAE,robert@gmail.com,3.457288e+09,DBT,70113,180296,04.05.2020,2016/07/15,NaN
4997,ACC104997,5875650079,Arun,saving,4579182.0,85525,49965,325034.0,16,banglore,Mumbai,United States,arun@gmail.com,8.212358e+09,DBT,57986,96335,24.05.2018,14/12/2021,Temp
4998,ACC104998,5322400117,Kumar,saving,3661381.0,19089,32079,69037.0,8,mumbay,Mumbai,Unites States,kumar@gmail,NaN,Crdit,-31084,180497,02.12.2018,11.06.2023,Remove
4999,ACC104999,5908194190,Mani,fixd depo,4227706.0,1980,21315,585174.0,14,NaN,Chennai,UAE,manigmail.com,NaN,DBT,-20849,-35976,29.04.2017,27-10-20,Temp

In [ ]:
df['Name'].unique()

array(['Divya', '  Aisha   ', 'Aisha', 'Robert', 'Kumar', 'John', 'Kavi',
       'Mani', 'Fatima', 'Arun', 'Priya', '  John   ', '  Divya   ',
       '  Kavi   ', '  Mani   ', '  Priya   ', '  Arun   ', '  Kumar   ',
       '  Robert   ', '  Fatima   '], dtype=object)

**A. Duplicates & Missing Values (10 Questions)**

1.	Identify and remove duplicate rows in the banking dataset.

In [ ]:
df.duplicated().sum()

np.int64(0)

2.	Identify duplicate Account_ID values and remove duplicates.

In [ ]:
df.duplicated(subset='Account_ID').sum()

np.int64(0)

3.	Identify customers with the same Name but different Account_Number (possible data mismatch)

In [ ]:

df.groupby('Name')['Account_Number'].nunique()

Name
  Aisha         51
  Arun          49
  Divya         47
  Fatima        54
  John          44
  Kavi          42
  Kumar         51
  Mani          47
  Priya         53
  Robert        46
Aisha          453
Arun           460
Divya          444
Fatima         438
John           461
Kavi           470
Kumar          441
Mani           448
Priya          434
Robert         467
Name: Account_Number, dtype: int64

4.	Fill missing Account_Type values with “Unknown”.

In [ ]:

df['Account_Type'].fillna('Unknown',inplace=True)

/tmp/ipykernel_12795/3604683510.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Account_Type'].fillna('Unknown',inplace=True)

5.	Fill missing Balance values with median balance of the branch.

In [ ]:

df['Balance'].fillna(df['Balance'].median(),inplace=True)

/tmp/ipykernel_12795/2997828524.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Balance'].fillna(df['Balance'].median(),inplace=True)

6.	Replace missing Branch values with most frequent branch.

In [ ]:

df['Branch'].fillna(df['Branch'].mode(),inplace=True)

/tmp/ipykernel_12795/1352612453.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Branch'].fillna(df['Branch'].mode(),inplace=True)

7.	Fill missing Loan_Amount values with 0.

In [ ]:

df['Loan_Amount'].fillna(0,inplace=True)

/tmp/ipykernel_12795/258122164.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Loan_Amount'].fillna(0,inplace=True)

In [ ]:
df['Name']=df['Name'].str.strip()

8.	Fill missing Country values using customer’s typical address records.

In [ ]:

df['Country'].fillna('unknown',inplace=True)
df['Branch'].fillna('unknown',inplace=True)

/tmp/ipykernel_12795/1323827130.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Country'].fillna('unknown',inplace=True)
/tmp/ipykernel_12795/1323827130.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Branch'].fillna('unknown',inplace=True)

9.	Replace missing Email entries with “noemail@bank.com”.

In [ ]:

df['Email'].fillna('noemail@bank.com',inplace=True)

/tmp/ipykernel_12795/3604872889.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Email'].fillna('noemail@bank.com',inplace=True)

10.	Replace missing Phone_Number entries with “0000000000”.

In [ ]:

df['Phone_Number'].fillna('0000000000',inplace=True)

/tmp/ipykernel_12795/3441465402.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Phone_Number'].fillna('0000000000',inplace=True)
/tmp/ipykernel_12795/3441465402.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0000000000' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df['Phone_Number'].fillna('0000000000',inplace=True)

**B. Invalid / Outlier Values (10 Questions)**

1.	Remove rows where Balance < 0 (invalid).

In [ ]:
for i in df.index:
  if df.loc[i,'Balance'] < 0:
    df.drop(i,inplace=True)

2.	Remove rows where Loan_Amount < 0

In [ ]:
for i in df.index:
  if df.loc[i,'Loan_Amount'] < 0:
    df.drop(i,inplace=True)

3.	Identify transactions where Withdrawal or Deposit is negative.

In [ ]:
neg=df[(df['Withdrawal'] < 0) | ( df['Deposit'] < 0) ]
print(neg.to_string())

     Account_ID  Account_Number    Name Account_Type    Balance  Fixed_Deposit  Recurring_Deposit  Loan_Amount  Interest_Rate     Branch      City        Country              Email  Phone_Number Transaction_Type  Withdrawal  Deposit Transaction_Date Account_Open_Date   Notes
3     ACC100003      9970006983  Robert       savngs  2249435.0          89789              24276     186769.0             14     chnnai       NaN  Unites States   robert@gmail.com  4798808687.0              DBT      -12935   173165       2022-05-19          04-02-19     NaN
4     ACC100004      9907953924   Kumar      Unknown  1702126.0          52251              22662     126330.0             16      Delhi  New York  Unites States   Kumar@@gmail.com   667427520.0            debit      168610   -10496       2019/01/25        14.05.2022     NaN
9     ACC100009      1487365080   Kumar       currnt   693974.0          60713              30306     877121.0              8     Mumbai     Delhi          Indai    kumar@gmail.com  8301044688.0           credit      -38889   -12496       2022/11/03        05.03.2021    Temp
10    ACC100010      8168249959  Fatima           FD  2417439.0           2557              38360    1567363.0              8  Hyderabad     Dubai          Indai  Fatima@@gmail.com    0000000000            debit      -43705    70885       04.12.2015        2022/11/09     NaN
16    ACC100016      1744293433    Arun      Savings  3127945.0          46175               7805          0.0              8      Delhi       NaN  United States     arun@gmail.com  4064562924.0           CREDIT      -44051   133062       2024-03-10        28.05.2018     NaN
19    ACC100019      7996256236   Aisha      Unknown  2417439.0          33496              23548     490328.0             12     Mumbai   Chennai          Indai   noemail@bank.com  8720231067.0           credit      -29642   -46733       06/02/2015          02-06-24   Check
28    ACC100028      3603500236   Priya       saving  3602692.0          45543              42783          0.0              8     delhii       NaN        unknown   Priya@@gmail.com  6991552105.0              DBT       71288   -11235       2023/04/26        2017-02-01     NaN
29    ACC100029      3746036109    John       currnt  4842472.0          81317              13051     471680.0             10  Bangalore   Chennai          Indai     john@gmail.com  1213850769.0              DBT      134943   -30802         20-12-20        2017/03/07   Check
31    ACC100031      1725570564  Fatima           RD  1900367.0          23061              13716    1900705.0              8   banglore     Dubai            UAE  Fatima@@gmail.com  9109898857.0              DBT      -21268    71465       18/11/2022          17-02-15    Temp
35    ACC100035      6402651504    Arun       currnt  4939847.0          53441                846     945614.0             10  Bangalore       NaN          India     arun@gmail.com  4595323030.0            DEBIT      -33611    72177       10.08.2020        07.11.2020     NaN
36    ACC100036      3287454186    John      Savings   814909.0          59383                  9     231983.0             14      Delhi  New York        unknown    John@@gmail.com  1713048087.0            debit       -7467   -48172       2024/07/22        23.01.2018     NaN
37    ACC100037      4139051895   Divya    fixd depo  4752116.0          73698               5415     217645.0             10    Chennai     Dubai          India    divya@gmail.com    0000000000           CREDIT      -37781   -49765       2017-05-22          06-06-18   Check
43    ACC100043      5440477172    Mani       savngs  1531530.0          94270               4757     834193.0              8   hydrebad   Chennai            UAE     mani@gmail.com   603803557.0           credit      -13632    87855       2019-11-28        2019/10/26     NaN
49    ACC100049      7874167563    Arun           FD  4717348.0          93065              11664    1079385.0             10     delhii       NaN          Indai     arun@gmail.com  9150243294.0            DEBIT      -33275   142468       20/08/2020        23.10.2024    Temp
50    ACC100050      6998563382   Priya      Current  1220896.0          89399              21792    1456554.0             10     mumbay  New York        unknown        priya@gmail  2230189148.0           credit      -38954   178071       06/11/2017        23.07.2019     NaN
53    ACC100053      9748881168   Kumar      Savings   788003.0          35435              30907    1326230.0             12     Mumbai       NaN            UAE    kumar@gmail.com  7966670358.0              DBT      -30574   -12735       2023/11/07        2015-01-16   Check
56    ACC100056      9514044710  Robert      Unknown  3138729.0          29757              34636     581652.0             12    Chennai     Delhi            UAE       robert@gmail  3735429189.0            DEBIT       74988    -4972              NaN        28/12/2021    Temp
58    ACC100058      2413264846   Aisha    fixd depo  2564235.0          50106              15585     481036.0             10     Mumbai     Delhi            UAE        aisha@gmail  7491544017.0              DBT       15160   -32398       14/11/2015        24.07.2021  Remove
60    ACC100060      8544693324    Mani       saving  2417439.0          87263              30220     460452.0             12   hydrebad   Chennai        unknown     mani@gmail.com   717252698.0           CREDIT      117581    -7466       06.12.2018          25-07-16    Temp
62    ACC100062      2647602123    Mani       saving  2417439.0           7813              31598    1153950.0             14  Bangalore  New York            UAE     mani@gmail.com  9691130286.0              DBT      -25140   102267         15-10-22        13/01/2021  Remove
69    ACC100069      5279221599    Kavi      Unknown  2926031.0          60315              14025     629282.0             14  Bangalore       NaN  Unites States      kavigmail.com  5060497343.0            debit      170971   -29951       2024/06/15        23.01.2022    Temp
93    ACC100093      2640418241  Robert           FD  2417439.0          50979              32125     593103.0             16     Mumbai   Chennai  Unites States  Robert@@gmail.com    0000000000            debit      -10721    59787       29/04/2015        2015-07-09     NaN
96    ACC100096      7623858346   Priya      Savings   267875.0           8706               8894    1718794.0             10      Delhi  New York  United States    priya@gmail.com  6847997042.0            DEBIT      129761    -5362       11.09.2023        2019-02-15     NaN
98    ACC100098      6876844675  Fatima       curent  1690687.0          18313              47639    1925090.0              8    unknown       NaN            UAE   noemail@bank.com  5457649538.0            Crdit      170894   -44890       09.05.2021        26.09.2023  Remove
102   ACC100102      6509350807   Divya      Unknown  2978149.0          74971              37766     531357.0             12   banglore     Delhi  United States     divyagmail.com  7959858373.0           CREDIT      193515   -42469       24.05.2017        2019/01/04    Temp
103   ACC100103      9159722110    John           FD   883396.0          48330               1171     823731.0             14    Chennai       NaN          India      johngmail.com  4997849414.0            debit      -32927    52304       20/10/2019        2023-04-20     NaN
105   ACC100105      5713995081   Priya       saving  1329904.0          12924               3750    1741881.0             12     chnnai  New York            UAE   noemail@bank.com    0000000000            Crdit      -36860    76468       2020-06-02        24/07/2016  Remove
108   ACC100108      5899318688  Robert       savngs  2417439.0          65031              33380    1516534.0             14     chnnai       NaN        unknown   robert@gmail.com  4355286064.0            Crdit      -12289   -43470       26/09/2015        08.11.2023     NaN
109   ACC100109      1399562882    Mani           FD  4177995.0          24217              23172     384341.0              8     Mumbai       NaN          India    Mani@@gmail.com  8351528184.0            DEBIT      148137   -23830       08/09/2017        2018-02-28     NaN
113   ACC100113      8415995454   Kumar       savngs   364994.0          94840              13074     931768.0             16     chnnai   Chennai            UAE    kumar@gmail.com  5437080738.0            DEBIT      140747   -44925       31/03/2017          29-10-19     NaN
115   ACC100115      3982642006  Fatima      Savings  4939904.0          71853              49678     994001.0             12     Mumbai  New York          Indai    fatimagmail.com  5742538236.0           credit        -121     9871         31-01-22          10-02-17  Remove
118   ACC100118      4991857278   Divya      Current  4999384.0          61035               8210    1584918.0             14     Mumbai  New York            UAE    divya@gmail.com  4096947866.0           credit       20028   -27793              NaN          19-02-20  Remove
119   ACC100119      5691327460    Kavi    fixd depo  4429825.0          78931              29808          0.0             16    unknown  New York  Unites States     kavi@gmail.com    0000000000            debit      150641   -11789         29-11-19          16-08-17    Temp
124   ACC100124      2655761004    Kavi       saving  1286092.0          27716               3236    1362236.0             12      Delhi     Delhi  United States   noemail@bank.com  5462291290.0              DBT      -29462    13918       18.01.2016          30-09-17     NaN
125   ACC100125      3493089371    John           FD  2794180.0          37772              26762     457243.0             16      Delhi  New York          India    John@@gmail.com  2175879246.0           credit      -49862    81430       2018/07/31        08.01.2022     NaN
129   ACC100129      4180320768   Aisha      Savings  2417439.0          78471               8068    1951447.0             10     chnnai   Chennai          India   Aisha@@gmail.com   321768135.0            debit      -38410    91958       28/06/2017          07-07-15     NaN
130   AC-100130      6581592079    John       savngs  3681404.0          12449              24297    1804188.0              8     chnnai     Delhi          India     john@gmail.com  1197162767.0            Crdit      -39793   168401       16/11/2017        2022/08/12    Temp
134   ACC100134      4062509460   Priya      Current  2091912.0          89963              33290    1037159.0              8     mumbay  New York            UAE    priya@gmail.com  8432249045.0           CREDIT      -26522    77881       2022-01-31          20-10-17  Remove
136   ACC100136      8064502251    Arun      Current  4759479.0          62261               8547          0.0             12  Hyderabad  New York            UAE         arun@gmail    0000000000            debit      177107    -2623       27.09.2020          28-04-15     NaN
138   ACC100138      3238949479   Aisha       curent  2485232.0          32245              44724          0.0             16     Mumbai     Delhi          India    aisha@gmail.com  8145648069.0            debit       52518   -30389       21.08.2020          01-04-19     NaN
141   ACC100141      3135940691    Mani      Current   302414.0          76721              27045     856792.0             12    unknown       NaN          Indai     mani@gmail.com  9445551925.0            Crdit      -13919    92105       31/07/2024        07/05/2016     NaN
143   ACC100143      8294190864    Kavi       curent  2761139.0          55745               5366    1235803.0             12     chnnai     Delhi            UAE    Kavi@@gmail.com  3060371558.0           CREDIT      180258   -24628       28.11.2024        2019/06/25     NaN
145   ACC100145      9239578786   Kumar           FD  4591094.0          20313              19149     600032.0              8  Bangalore  New York  United States        kumar@gmail  3413010993.0            DEBIT      -21518   -40829         13-07-18        11/11/2015     NaN
150   ACC100150      8341477065  Robert       saving  2600324.0          78077               8712    1303428.0             12   banglore   Chennai  Unites States   noemail@bank.com  5803384450.0              DBT      -31625   -34912         19-10-19        23.02.2022     NaN
151   ACC100151      1524116974   Divya       saving   551891.0          19873              13050          0.0             10     chnnai       NaN          Indai    divya@gmail.com  5533420060.0            DEBIT      -39272    45102       2019-02-06          07-09-23   Check
152   ACC100152      7940288800   Aisha           FD  4457167.0          79747              23255     119887.0             16     Mumbai       NaN          Indai    aisha@gmail.com  8007240457.0           CREDIT      -16081    23155         30-01-20        15.02.2019   Check
153   ACC100153      1304476999  Fatima      Current   247675.0          11889              24335     698175.0             12  Hyderabad     Dubai            UAE   noemail@bank.com  3700440504.0              DBT      -45014   -17702       2022/12/03        2023-08-07     NaN
160   ACC100160      6888885225  Robert       savngs  4516701.0          24170               8024     352441.0             16   banglore   Chennai          India       robert@gmail   548174195.0            Crdit      -49131    47088       2021/10/03        2024/02/06     NaN
162   ACC100162      4968665189  Robert      Savings  3252198.0          35529              47963     287986.0             10     mumbay   Chennai            UAE   robert@gmail.com  3223403796.0              DBT      -36739    26709       02.03.2015          13-04-24     NaN
164   ACC100164      1688764188   Kumar       saving    26240.0          23199              44589     225595.0             10    Chennai  New York  United States     kumargmail.com   674145155.0            debit      171135   -33678       21/12/2016        2016/09/29  Remove
167   ACC100167      4140980533  Fatima      Unknown   514430.0          33272              42581    1561356.0             10  Bangalore       NaN            UAE   fatima@gmail.com  2586221824.0              DBT      -13532   111770         05-10-20        2018-06-09  Remove
172   ACC100172      8673853911   Aisha           RD  2039934.0            203              16544    1531326.0             14     Mumbai  New York  Unites States    aisha@gmail.com    0000000000            debit       -6605   105103       29/12/2017        2023/01/19    Temp
175   ACC100175      6890487265    John       saving  2448578.0          70532              44594    1704858.0             16     chnnai    Mumbai            UAE     john@gmail.com  5093581651.0            DEBIT      117361   -16660       03/01/2018        13/05/2021     NaN
176   ACC100176      3785883112    John           FD  3317851.0          95040               6982    1533812.0             12     chnnai    Mumbai  United States   noemail@bank.com  5510131067.0            Crdit      -13818    66136       2024/01/07        2021-01-22    Temp
180   ACC100180      8769697365    John      Unknown   727635.0          12453              18814     703340.0             12    unknown       NaN        unknown     john@gmail.com  5164597726.0              DBT      164028   -33649       01.02.2024        2022-08-14   Check
182   ACC100182      5824247183   Kumar       currnt  1409410.0          35303              34700    1569451.0              8  Bangalore   Chennai  Unites States        kumar@gmail  5289536785.0           CREDIT       12790   -18520         07-12-20        2015-08-08    Temp
184   ACC100184      1653043637    Arun      Current  2836569.0          51148              48400     481121.0             10   hydrebad     Dubai            UAE    Arun@@gmail.com  6779640861.0              DBT      154720    -8765       22.10.2024        2017-07-01   Check
186   ACC100186      2443139359  Fatima       saving  2197680.0          89037              13304     458011.0             10  Hyderabad  New York        unknown   fatima@gmail.com   792600944.0            debit      -14446    -3078         11-05-19          25-01-16     NaN
199   ACC100199      1034613597    Kavi       currnt  4364011.0          39531               3164     231249.0             14     mumbay     Dubai  United States     kavi@gmail.com  1798493572.0            DEBIT      -12966   121389       2017-03-21        2018/11/25     NaN
200   ACC100200      4681610143   Aisha           RD  3830323.0          40469              17600     535726.0             14     delhii     Dubai        unknown    aisha@gmail.com  9286010886.0            DEBIT        8819    -6144       2015/05/05        21/11/2023  Remove
201   ACC100201      3428460279    John           FD  2423006.0          66253              19945          0.0              8   banglore   Chennai  Unites States   noemail@bank.com  6882319244.0              DBT       -3665    -3194       29.01.2023          25-12-21     NaN
202   ACC100202      2802285865   Priya           RD  3574656.0          90895              24816          0.0             10      Delhi       NaN          India   noemail@bank.com  9589365197.0            debit      149549   -44305       2020/03/17        2020/03/25  Remove
206   ACC100206      6805958302  Fatima      Savings  4895697.0          54460              35230    1004348.0              8     Mumbai  New York          Indai   noemail@bank.com  1391170647.0            debit       70617   -10440         05-06-17        2015-12-07     NaN
212   ACC100212      7902593452    John       saving  1454900.0          30791              42230    1283512.0              8   banglore  New York            UAE   noemail@bank.com  6575923209.0            debit       -1076    97781       09/05/2015        2020-02-16     NaN
213   ACC100213      2102704915  Robert    fixd depo  3190641.0          86005              40722     608396.0             12      Delhi   Chennai          India   noemail@bank.com  8534527379.0           CREDIT      -42507    19639         28-04-22          15-11-17    Temp
217   ACC100217      7019232485   Kumar      Current  3517945.0           5867              15284    1559417.0             16     mumbay    Mumbai  United States    kumar@gmail.com    0000000000           credit       33384   -49610       16/05/2016        2016/12/30     NaN
221   ACC100221      1292526039   Aisha           RD   675571.0          84101              26025     818282.0             12   hydrebad  New York            UAE    aisha@gmail.com  6626089546.0              DBT      159617   -22157         22-07-23        2016-04-24  Remove
224   ACC100224      9791682072  Fatima       savngs  3033128.0          59213              27281      92166.0             10      Delhi     Delhi  United States       fatima@gmail  2787303812.0            debit      -35494   175413       2019/03/22        22/06/2020   Check
225   ACC100225      1416464408  Fatima       savngs  1102791.0          84817              42049    1803935.0             12   banglore     Dubai        unknown   fatima@gmail.com  1862264957.0            debit      -17770    34573       16.07.2016        2023/03/06  Remove
227   ACC100227      3550268394    John           RD  2600196.0          83860              31334    1372296.0             16    unknown       NaN          Indai     john@gmail.com  1727296135.0            debit       68248   -39696       02.09.2015        26.11.2020  Remove
229   ACC100229      1843077603    Kavi           FD  1474960.0          93309              19937     477063.0             14    unknown     Dubai        unknown      kavigmail.com  2628528092.0           credit      152258    -4799       15/02/2020        2022/12/29   Check

4.	Fix invalid Transaction_Date formats (yyyy/mm/dd, dd-mm-yy).

In [ ]:
df['Transaction_Date']=pd.to_datetime(df['Transaction_Date'],format='mixed')
df['Transaction_Date']=df['Transaction_Date'].dt.strftime('%d-%m-%y')

5.	Correct typos in Branch (“mumbay”, “chnnai”, “delhii”).

In [ ]:
df['Branch'].replace({'delhii':'Delhi','mumbay':'Mumbai','chnnai':'Chennai','banglore':'Bangalore','hydrebad':'Hyderabad'},inplace=True)

/tmp/ipykernel_12795/3866515531.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Branch'].replace({'delhii':'Delhi','mumbay':'Mumbai','chnnai':'Chennai','banglore':'Bangalore','hydrebad':'Hyderabad'},inplace=True)

6.	Correct typos in Account_Type (“savngs”, “curent”, “fixd depo”).

In [ ]:
df['Account_Type'].replace({'fixd depo':'FD','savngs':'Savings','curent':'Current','currnt':'Current','saving':'Savings'},inplace=True)

/tmp/ipykernel_12795/2069395748.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Account_Type'].replace({'fixd depo':'FD','savngs':'Savings','curent':'Current','currnt':'Current','saving':'Savings'},inplace=True)

7.	Standardize Country names (Indai, Unites States, UAE ).

In [ ]:
df['Country'].replace({'Indai':'India','United States':'Unites States'},inplace=True)

/tmp/ipykernel_12795/763055798.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Country'].replace({'Indai':'India','United States':'Unites States'},inplace=True)

8.	Replace unrealistic Loan_Amount values (> 1 crore).

In [ ]:
c=0
for i in df.index:
  if df.loc[i,'Loan_Amount'] > 10000000:
    df.loc[i,'Loan_Amount'].replace('Unrealistic Amount')

9.	Remove invalid Email formats.

In [ ]:

for i in df.index:
  if '@' not in df.loc[i,'Email']:
    df.drop(i,inplace=True)
  elif '.com' not in df.loc[i,'Email']:
    df.drop(i,inplace=True)
  elif '@@' in df.loc[i,'Email']:
    df.drop(i,inplace=True)

10.	Fix inconsistent Transaction_Type (CREDIT, Crdit, Debit, DBT).

In [ ]:
for i in df.index:
  if df.loc[i,'Transaction_Type'] == 'CREDIT':
    df.loc[i,'Transaction_Type'] = 'Credit'
  elif df.loc[i,'Transaction_Type'] == 'Crdit':
    df.loc[i,'Transaction_Type'] = 'Credit'
  elif df.loc[i,'Transaction_Type'] == 'Debit':
    df.loc[i,'Transaction_Type'] = 'DBT'

**C. Conditional Fetch / Filtering (10 Questions)**

1.	Fetch customers with Balance > 10,00,000.

In [ ]:
for i in df.index:
  if df.loc[i,'Balance'] > 1000000:
    print(pd.DataFrame(df.loc[i,['Account_ID','Name']]))

Streaming output truncated to the last 5000 lines.
Account_ID  ACC101704
Name             John
                 1705
Account_ID  ACC101705
Name             John
                 1706
Account_ID  ACC101706
Name            Aisha
                 1707
Account_ID  ACC101707
Name             John
                 1710
Account_ID  ACC101710
Name           Robert
                 1712
Account_ID  ACC101712
Name             Arun
                 1713
Account_ID  AC-101713
Name           Robert
                 1714
Account_ID  ACC101714
Name             Arun
                 1716
Account_ID  ACC101716
Name             Kavi
                 1721
Account_ID  ACC101721
Name             John
                 1722
Account_ID  ACC101722
Name            Kumar
                 1727
Account_ID  ACC101727
Name            Priya
                 1731
Account_ID  ACC101731
Name           Robert
                 1732
Account_ID  ACC101732
Name           Robert
                 1736
Account_ID  ACC101736
Name           Fatima
                 1741
Account_ID  ACC101741
Name            Kumar
                 1742
Account_ID  ACC101742
Name           Robert
                 1744
Account_ID  ACC101744
Name             Mani
                 1745
Account_ID  ACC101745
Name            Aisha
                 1746
Account_ID  ACC101746
Name           Fatima
                 1749
Account_ID  ACC101749
Name            Aisha
                 1750
Account_ID  ACC101750
Name             John
                 1751
Account_ID  ACC101751
Name            Divya
                 1753
Account_ID  ACC101753
Name           Fatima
                 1754
Account_ID  ACC101754
Name           Robert
                 1755
Account_ID  ACC101755
Name             Arun
                 1756
Account_ID  ACC101756
Name            Aisha
                 1758
Account_ID  ACC101758
Name             Kavi
                 1759
Account_ID  ACC101759
Name             Kavi
                 1762
Account_ID  ACC101762
Name            Kumar
                 1763
Account_ID  ACC101763
Name             Kavi
                 1765
Account_ID  ACC101765
Name            Divya
                 1766
Account_ID  ACC101766
Name           Fatima
                 1767
Account_ID  ACC101767
Name            Kumar
                 1774
Account_ID  ACC101774
Name           Robert
                 1776
Account_ID  ACC101776
Name             John
                 1777
Account_ID  ACC101777
Name            Priya
                 1778
Account_ID  ACC101778
Name            Kumar
                 1790
Account_ID  ACC101790
Name             John
                 1792
Account_ID  ACC101792
Name             Kavi
                 1793
Account_ID  ACC101793
Name             Mani
                 1796
Account_ID  ACC101796
Name             Arun
                 1797
Account_ID  ACC101797
Name            Divya
                 1799
Account_ID  ACC101799
Name            Aisha
                 1800
Account_ID  ACC101800
Name             John
                 1801
Account_ID  ACC101801
Name             Mani
                 1804
Account_ID  ACC101804
Name            Aisha
                 1806
Account_ID  ACC101806
Name            Kumar
                 1808
Account_ID  ACC101808
Name           Robert
                 1810
Account_ID  ACC101810
Name             John
                 1811
Account_ID  ACC101811
Name            Divya
                 1815
Account_ID  ACC101815
Name             Mani
                 1816
Account_ID  ACC101816
Name            Priya
                 1817
Account_ID  ACC101817
Name            Priya
                 1818
Account_ID  ACC101818
Name           Fatima
                 1819
Account_ID  ACC101819
Name             Arun
                 1821
Account_ID  ACC101821
Name             Kavi
                 1823
Account_ID  ACC101823
Name             Kavi
                 1825
Account_ID  ACC101825
Name             Kavi
                 1827
Account_ID  ACC101827
Name             Mani
                 1831
Account_ID  ACC101831
Name            Priya
                 1832
Account_ID  ACC101832
Name             Kavi
                 1834
Account_ID  ACC101834
Name            Divya
                 1836
Account_ID  ACC101836
Name             Kavi
                 1839
Account_ID  ACC101839
Name            Aisha
                 1841
Account_ID  ACC101841
Name           Robert
                 1842
Account_ID  ACC101842
Name             Kavi
                 1843
Account_ID  ACC101843
Name            Kumar
                 1844
Account_ID  ACC101844
Name            Kumar
                 1846
Account_ID  ACC101846
Name            Aisha
                 1848
Account_ID  ACC101848
Name             John
                 1850
Account_ID  ACC101850
Name            Divya
                 1851
Account_ID  ACC101851
Name            Divya
                 1852
Account_ID  ACC101852
Name             Mani
                 1853
Account_ID  ACC101853
Name           Fatima
                 1855
Account_ID  ACC101855
Name           Fatima
                 1858
Account_ID  ACC101858
Name            Divya
                 1859
Account_ID  ACC101859
Name             Kavi
                 1861
Account_ID  ACC101861
Name            Priya
                 1863
Account_ID  AC-101863
Name             John
                 1864
Account_ID  ACC101864
Name           Fatima
                 1865
Account_ID  ACC101865
Name           Fatima
                 1868
Account_ID  ACC101868
Name             John
                 1871
Account_ID  ACC101871
Name             Mani
                 1872
Account_ID  ACC101872
Name           Robert
                 1876
Account_ID  ACC101876
Name             Arun
                 1877
Account_ID  ACC101877
Name           Robert
                 1878
Account_ID  ACC101878
Name             Arun
                 1880
Account_ID  ACC101880
Name             Kavi
                 1883
Account_ID  ACC101883
Name             John
                 1884
Account_ID  ACC101884
Name            Aisha
                 1885
Account_ID  ACC101885
Name             John
                 1887
Account_ID  ACC101887
Name            Kumar
                 1888
Account_ID  ACC101888
Name             John
                 1889
Account_ID  ACC101889
Name             Mani
                 1894
Account_ID  ACC101894
Name           Fatima
                 1895
Account_ID  ACC101895
Name             Arun
                 1897
Account_ID  ACC101897
Name             John
                 1899
Account_ID  ACC101899
Name            Divya
                 1900
Account_ID  ACC101900
Name           Robert
                 1903
Account_ID  ACC101903
Name            Aisha
                 1904
Account_ID  ACC101904
Name             John
                 1906
Account_ID  ACC101906
Name           Fatima
                 1914
Account_ID  ACC101914
Name             Arun
                 1915
Account_ID  ACC101915
Name            Priya
                 1917
Account_ID  ACC101917
Name           Fatima
                 1920
Account_ID  ACC101920
Name           Robert
                 1921
Account_ID  ACC101921
Name            Aisha
                 1922
Account_ID  ACC101922
Name            Aisha
                 1923
Account_ID  ACC101923
Name            Priya
                 1924
Account_ID  ACC101924
Name           Fatima
                 1925
Account_ID  ACC101925
Name            Priya
                 1926
Account_ID  ACC101926
Name             Arun
                 1927
Account_ID  ACC101927
Name            Kumar
                 1928
Account_ID  ACC101928
Name             Arun
                 1929
Account_ID  ACC101929
Name            Priya
                 1933
Account_ID  ACC101933
Name           Fatima
                 1936
Account_ID  ACC101936
Name            Priya
                 1937
Account_ID  ACC101937
Name           Fatima
                 1938
Account_ID  ACC101938
Name            Aisha
                 1941
Account_ID  ACC101941
Name             Kavi
                 1942
Account_ID  ACC101942
Name            Aisha
                 1943
Account_ID  ACC101943
Name             Arun
                 1944
Account_ID  ACC101944
Name           Robert
                 1947
Account_ID  ACC101947
Name           Fatima
                 1952
Account_ID  ACC101952
Name             John
                 1953
Account_ID  ACC101953
Name            Priya
                 1954
Account_ID  ACC101954
Name             John
                 1958
Account_ID  ACC101958
Name           Robert
                 1960
Account_ID  ACC101960
Name            Priya
                 1961
Account_ID  ACC101961
Name             John
                 1963
Account_ID  ACC101963
Name            Kumar
                 1964
Account_ID  ACC101964
Name             Mani
                 1966
Account_ID  ACC101966
Name           Robert
                 1967
Account_ID  ACC101967
Name             John
                 1971
Account_ID  ACC101971
Name             Mani
                 1972
Account_ID  ACC101972
Name            Priya
                 1976
Account_ID  ACC101976
Name             Mani
                 1978
Account_ID  AC-101978
Name             Mani
                 1979
Account_ID  ACC101979
Name           Fatima
                 1980
Account_ID  ACC101980
Name             Mani
                 1981
Account_ID  ACC101981
Name             Kavi
                 1982
Account_ID  AC-101982
Name             John
                 1983
Account_ID  ACC101983
Name             John
                 1984
Account_ID  ACC101984
Name             Kavi
                 1990
Account_ID  ACC101990
Name             Arun
                 1991
Account_ID  ACC101991
Name            Aisha
                 1992
Account_ID  ACC101992
Name           Robert
                 1993
Account_ID  ACC101993
Name             Kavi
                 1999
Account_ID  ACC101999
Name            Priya
                 2001
Account_ID  ACC102001
Name             Arun
                 2002
Account_ID  AC-102002
Name           Robert
                 2004
Account_ID  ACC102004
Name             Arun
                 2009
Account_ID  ACC102009
Name             Kavi
                 2010
Account_ID  ACC102010
Name            Priya
                 2011
Account_ID  ACC102011
Name             Mani
                 2015
Account_ID  ACC102015
Name             Arun
                 2019
Account_ID  ACC102019
Name             Kavi
                 2020
Account_ID  ACC102020
Name            Priya
                 2024
Account_ID  ACC102024
Name           Robert
                 2025
Account_ID  ACC102025
Name           Fatima
                 2027
Account_ID  ACC102027
Name           Fatima
                 2028
Account_ID  ACC102028
Name            Kumar
                 2029
Account_ID  ACC102029
Name            Priya
                 2030
Account_ID  ACC102030
Name             Kavi
                 2033
Account_ID  ACC102033
Name             Kavi
                 2035
Account_ID  ACC102035
Name             John
                 2037
Account_ID  ACC102037
Name            Aisha
                 2039
Account_ID  ACC102039
Name            Priya
                 2040
Account_ID  ACC102040
Name             Kavi
                 2041
Account_ID  ACC102041
Name            Priya
                 2042
Account_ID  ACC102042
Name           Robert
                 2043
Account_ID  ACC102043
Name            Aisha
                 2047
Account_ID  ACC102047
Name            Priya
                 2048
Account_ID  ACC102048
Name           Fatima
                 2049
Account_ID  ACC102049
Name            Divya
                 2050
Account_ID  ACC102050
Name           Fatima
                 2051
Account_ID  ACC102051
Name            Divya
                 2054
Account_ID  ACC102054
Name            Aisha
                 2055
Account_ID  AC-102055
Name           Robert
                 2057
Account_ID  ACC102057
Name           Fatima
                 2060
Account_ID  ACC102060
Name             Kavi
                 2061
Account_ID  ACC102061
Name             Arun
                 2063
Account_ID  ACC102063
Name           Robert
                 2065
Account_ID  ACC102065
Name            Priya
                 2066
Account_ID  ACC102066
Name             Kavi
                 2067
Account_ID  ACC102067
Name            Aisha
                 2068
Account_ID  ACC102068
Name           Robert
                 2070
Account_ID  ACC102070
Name             Arun
                 2076
Account_ID  ACC102076
Name            Kumar
                 2077
Account_ID  ACC102077
Name           Robert
                 2078
Account_ID  ACC102078
Name            Priya
                 2079
Account_ID  ACC102079
Name           Fatima
                 2081
Account_ID  ACC102081
Name            Priya
                 2082
Account_ID  ACC102082
Name           Fatima
                 2083
Account_ID  ACC102083
Name             Mani
                 2088
Account_ID  ACC102088
Name            Kumar
                 2089
Account_ID  ACC102089
Name             Kavi
                 2090
Account_ID  ACC102090
Name            Aisha
                 2095
Account_ID  ACC102095
Name           Robert
                 2096
Account_ID  ACC102096
Name            Priya
                 2099
Account_ID  ACC102099
Name            Divya
                 2100
Account_ID  ACC102100
Name           Robert
                 2101
Account_ID  ACC102101
Name           Fatima
                 2104
Account_ID  ACC102104
Name           Fatima
                 2106
Account_ID  ACC102106
Name            Kumar
                 2107
Account_ID  ACC102107
Name           Fatima
                 2108
Account_ID  ACC102108
Name            Divya
                 2110
Account_ID  ACC102110
Name             Kavi
                 2111
Account_ID  ACC102111
Name            Aisha
                 2112
Account_ID  ACC102112
Name           Fatima
                 2114
Account_ID  ACC102114
Name             Mani
                 2115
Account_ID  ACC102115
Name             Arun
                 2116
Account_ID  ACC102116
Name           Robert
                 2117
Account_ID  AC-102117
Name            Kumar
                 2119
Account_ID  ACC102119
Name             Arun
                 2122
Account_ID  ACC102122
Name             Mani
                 2123
Account_ID  ACC102123
Name             John
                 2128
Account_ID  ACC102128
Name             Kavi
                 2129
Account_ID  ACC102129
Name             John
                 2131
Account_ID  ACC102131
Name             Arun
                 2133
Account_ID  ACC102133
Name            Kumar
                 2135
Account_ID  ACC102135
Name            Divya
                 2136
Account_ID  ACC102136
Name           Fatima
                 2139
Account_ID  ACC102139
Name             John
                 2142
Account_ID  ACC102142
Name            Divya
                 2144
Account_ID  ACC102144
Name            Divya
                 2145
Account_ID  ACC102145
Name             Arun
                 2151
Account_ID  ACC102151
Name            Priya
                 2153
Account_ID  ACC102153
Name             Arun
                 2154
Account_ID  ACC102154
Name             John
                 2155
Account_ID  ACC102155
Name             Arun
                 2156
Account_ID  ACC102156
Name            Divya
                 2157
Account_ID  ACC102157
Name            Aisha
                 2158
Account_ID  ACC102158
Name            Kumar
                 2159
Account_ID  ACC102159
Name           Robert
                 2160
Account_ID  ACC102160
Name           Fatima
                 2162
Account_ID  ACC102162
Name             Arun
                 2163
Account_ID  ACC102163
Name             Mani
                 2164
Account_ID  ACC102164
Name            Aisha
                 2165
Account_ID  ACC102165
Name            Priya
                 2167
Account_ID  ACC102167
Name            Aisha
                 2168
Account_ID  ACC102168
Name             Arun
                 2169
Account_ID  ACC102169
Name           Fatima
                 2170
Account_ID  ACC102170
Name            Aisha
                 2171
Account_ID  ACC102171
Name           Fatima
                 2172
Account_ID  ACC102172
Name            Priya
                 2173
Account_ID  ACC102173
Name             John
                 2174
Account_ID  ACC102174
Name             Mani
                 2175
Account_ID  ACC102175
Name           Robert
                 2176
Account_ID  ACC102176
Name            Kumar
                 2177
Account_ID  ACC102177
Name            Divya
                 2180
Account_ID  ACC102180
Name           Robert
                 2182
Account_ID  ACC102182
Name            Aisha
                 2183
Account_ID  ACC102183
Name             John
                 2187
Account_ID  ACC102187
Name             Kavi
                 2188
Account_ID  ACC102188
Name             Kavi
                 2190
Account_ID  ACC102190
Name            Divya
                 2191
Account_ID  ACC102191
Name           Robert
                 2193
Account_ID  ACC102193
Name            Priya
                 2194
Account_ID  ACC102194
Name            Divya
                 2196
Account_ID  ACC102196
Name           Fatima
                 2198
Account_ID  ACC102198
Name           Fatima
                 2202
Account_ID  ACC102202
Name             Mani
                 2205
Account_ID  ACC102205
Name            Priya
                 2206
Account_ID  ACC102206
Name             Kavi
                 2209
Account_ID  ACC102209
Name             Arun
                 2210
Account_ID  ACC102210
Name            Priya
                 2211
Account_ID  ACC102211
Name           Fatima
                 2212
Account_ID  ACC102212
Name            Divya
                 2213
Account_ID  ACC102213
Name            Priya
                 2214
Account_ID  ACC102214
Name             Mani
                 2216
Account_ID  ACC102216
Name           Robert
                 2217
Account_ID  ACC102217
Name            Priya
                 2224
Account_ID  ACC102224
Name            Priya
                 2228
Account_ID  ACC102228
Name             Arun
                 2230
Account_ID  ACC102230
Name           Robert
                 2232
Account_ID  ACC102232
Name             Mani
                 2233
Account_ID  ACC102233
Name           Robert
                 2234
Account_ID  ACC102234
Name             Kavi
                 2236
Account_ID  ACC102236
Name             Kavi
                 2237
Account_ID  ACC102237
Name           Fatima
                 2238
Account_ID  ACC102238
Name            Divya
                 2239
Account_ID  ACC102239
Name            Aisha
                 2244
Account_ID  ACC102244
Name            Divya
                 2245
Account_ID  AC-102245
Name            Divya
                 2247
Account_ID  ACC102247
Name           Fatima
                 2249
Account_ID  ACC102249
Name             John
                 2250
Account_ID  ACC102250
Name             John
                 2251
Account_ID  ACC102251
Name            Aisha
                 2252
Account_ID  ACC102252
Name             John
                 2254
Account_ID  ACC102254
Name            Priya
                 2255
Account_ID  ACC102255
Name             Mani
                 2256
Account_ID  ACC102256
Name             Mani
                 2258
Account_ID  ACC102258
Name            Divya
                 2263
Account_ID  ACC102263
Name             John
                 2265
Account_ID  ACC102265
Name             Mani
                 2266
Account_ID  ACC102266
Name           Robert
                 2267
Account_ID  ACC102267
Name             Kavi
                 2269
Account_ID  ACC102269
Name             Arun
                 2270
Account_ID  ACC102270
Name            Kumar
                 2273
Account_ID  ACC102273
Name            Kumar
                 2274

2.	Fetch customers with Loan_Amount > 5,00,000.

In [ ]:
for i in df.index:
  if df.loc[i,'Loan_Amount'] > 500000:
        print(pd.DataFrame(df.loc[i,['Account_ID','Name']]))

Streaming output truncated to the last 5000 lines.
Account_ID  ACC101026
Name            Priya
                 1027
Account_ID  ACC101027
Name           Fatima
                 1031
Account_ID  ACC101031
Name            Kumar
                 1032
Account_ID  ACC101032
Name            Divya
                 1036
Account_ID  ACC101036
Name            Aisha
                 1037
Account_ID  ACC101037
Name            Kumar
                 1043
Account_ID  ACC101043
Name            Aisha
                 1046
Account_ID  ACC101046
Name           Robert
                 1048
Account_ID  ACC101048
Name           Fatima
                 1056
Account_ID  ACC101056
Name            Divya
                 1057
Account_ID  ACC101057
Name             John
                 1059
Account_ID  ACC101059
Name             Arun
                 1061
Account_ID  ACC101061
Name            Priya
                 1065
Account_ID  ACC101065
Name           Robert
                 1069
Account_ID  ACC101069
Name           Fatima
                 1073
Account_ID  ACC101073
Name             Arun
                 1077
Account_ID  ACC101077
Name            Kumar
                 1080
Account_ID  ACC101080
Name            Divya
                 1081
Account_ID  AC-101081
Name           Fatima
                 1084
Account_ID  ACC101084
Name           Robert
                 1088
Account_ID  ACC101088
Name            Aisha
                 1093
Account_ID  ACC101093
Name            Priya
                 1095
Account_ID  ACC101095
Name            Aisha
                 1098
Account_ID  ACC101098
Name             Mani
                 1100
Account_ID  ACC101100
Name             Mani
                 1102
Account_ID  ACC101102
Name            Aisha
                 1105
Account_ID  ACC101105
Name           Robert
                 1109
Account_ID  ACC101109
Name            Aisha
                 1110
Account_ID  ACC101110
Name           Robert
                 1111
Account_ID  ACC101111
Name            Kumar
                 1112
Account_ID  ACC101112
Name             Arun
                 1114
Account_ID  ACC101114
Name           Fatima
                 1116
Account_ID  ACC101116
Name            Aisha
                 1117
Account_ID  ACC101117
Name             Kavi
                 1119
Account_ID  ACC101119
Name             Kavi
                 1124
Account_ID  ACC101124
Name            Kumar
                 1125
Account_ID  AC-101125
Name             Arun
                 1129
Account_ID  ACC101129
Name           Robert
                 1136
Account_ID  ACC101136
Name           Fatima
                 1138
Account_ID  ACC101138
Name             Arun
                 1139
Account_ID  ACC101139
Name             John
                 1142
Account_ID  ACC101142
Name            Kumar
                 1143
Account_ID  ACC101143
Name           Robert
                 1145
Account_ID  ACC101145
Name            Kumar
                 1153
Account_ID  ACC101153
Name           Robert
                 1155
Account_ID  ACC101155
Name            Priya
                 1156
Account_ID  ACC101156
Name           Robert
                 1157
Account_ID  ACC101157
Name             Mani
                 1160
Account_ID  ACC101160
Name             Mani
                 1161
Account_ID  ACC101161
Name           Fatima
                 1164
Account_ID  ACC101164
Name            Kumar
                 1165
Account_ID  ACC101165
Name             Arun
                 1167
Account_ID  ACC101167
Name           Fatima
                 1168
Account_ID  ACC101168
Name             Arun
                 1171
Account_ID  ACC101171
Name            Aisha
                 1173
Account_ID  ACC101173
Name            Divya
                 1178
Account_ID  ACC101178
Name             Kavi
                 1181
Account_ID  ACC101181
Name            Priya
                 1184
Account_ID  ACC101184
Name           Robert
                 1187
Account_ID  ACC101187
Name            Aisha
                 1189
Account_ID  ACC101189
Name           Fatima
                 1190
Account_ID  ACC101190
Name            Divya
                 1191
Account_ID  ACC101191
Name            Aisha
                 1193
Account_ID  ACC101193
Name           Robert
                 1194
Account_ID  ACC101194
Name            Divya
                 1197
Account_ID  ACC101197
Name            Priya
                 1201
Account_ID  ACC101201
Name             Arun
                 1204
Account_ID  ACC101204
Name            Priya
                 1211
Account_ID  ACC101211
Name             John
                 1213
Account_ID  ACC101213
Name             John
                 1214
Account_ID  ACC101214
Name             Kavi
                 1215
Account_ID  ACC101215
Name            Kumar
                 1216
Account_ID  ACC101216
Name            Divya
                 1218
Account_ID  ACC101218
Name             Kavi
                 1221
Account_ID  ACC101221
Name             Mani
                 1224
Account_ID  ACC101224
Name            Priya
                 1226
Account_ID  ACC101226
Name             Kavi
                 1228
Account_ID  ACC101228
Name             Arun
                 1231
Account_ID  ACC101231
Name           Robert
                 1233
Account_ID  ACC101233
Name           Robert
                 1234
Account_ID  ACC101234
Name             John
                 1236
Account_ID  ACC101236
Name             Arun
                 1237
Account_ID  ACC101237
Name           Robert
                 1240
Account_ID  ACC101240
Name            Aisha
                 1241
Account_ID  ACC101241
Name            Divya
                 1255
Account_ID  ACC101255
Name            Divya
                 1258
Account_ID  ACC101258
Name            Divya
                 1260
Account_ID  ACC101260
Name             Arun
                 1265
Account_ID  ACC101265
Name           Fatima
                 1267
Account_ID  ACC101267
Name            Aisha
                 1268
Account_ID  ACC101268
Name           Fatima
                 1269
Account_ID  ACC101269
Name            Aisha
                 1271
Account_ID  ACC101271
Name            Kumar
                 1273
Account_ID  ACC101273
Name             Arun
                 1274
Account_ID  ACC101274
Name             Arun
                 1275
Account_ID  ACC101275
Name           Fatima
                 1277
Account_ID  ACC101277
Name            Aisha
                 1281
Account_ID  ACC101281
Name            Kumar
                 1282
Account_ID  ACC101282
Name            Aisha
                 1283
Account_ID  ACC101283
Name             Mani
                 1285
Account_ID  ACC101285
Name            Kumar
                 1287
Account_ID  ACC101287
Name            Aisha
                 1288
Account_ID  AC-101288
Name           Fatima
                 1289
Account_ID  ACC101289
Name            Aisha
                 1290
Account_ID  ACC101290
Name             Kavi
                 1295
Account_ID  ACC101295
Name             John
                 1296
Account_ID  ACC101296
Name            Aisha
                 1299
Account_ID  ACC101299
Name             Kavi
                 1301
Account_ID  ACC101301
Name             Arun
                 1302
Account_ID  ACC101302
Name            Divya
                 1304
Account_ID  ACC101304
Name             Kavi
                 1311
Account_ID  ACC101311
Name           Fatima
                 1312
Account_ID  ACC101312
Name             John
                 1313
Account_ID  ACC101313
Name             John
                 1314
Account_ID  ACC101314
Name           Robert
                 1315
Account_ID  ACC101315
Name            Priya
                 1318
Account_ID  ACC101318
Name            Kumar
                 1321
Account_ID  ACC101321
Name            Priya
                 1322
Account_ID  ACC101322
Name           Robert
                 1325
Account_ID  ACC101325
Name            Divya
                 1326
Account_ID  ACC101326
Name             Arun
                 1328
Account_ID  ACC101328
Name             Arun
                 1329
Account_ID  ACC101329
Name            Priya
                 1332
Account_ID  ACC101332
Name             Arun
                 1336
Account_ID  ACC101336
Name             John
                 1338
Account_ID  ACC101338
Name           Fatima
                 1347
Account_ID  ACC101347
Name           Robert
                 1351
Account_ID  ACC101351
Name           Robert
                 1352
Account_ID  ACC101352
Name             Mani
                 1355
Account_ID  ACC101355
Name             Mani
                 1357
Account_ID  ACC101357
Name           Robert
                 1359
Account_ID  ACC101359
Name            Divya
                 1365
Account_ID  ACC101365
Name           Fatima
                 1366
Account_ID  ACC101366
Name             Kavi
                 1367
Account_ID  ACC101367
Name            Divya
                 1370
Account_ID  ACC101370
Name             Kavi
                 1371
Account_ID  ACC101371
Name            Aisha
                 1379
Account_ID  ACC101379
Name             Kavi
                 1380
Account_ID  ACC101380
Name             John
                 1382
Account_ID  ACC101382
Name            Divya
                 1385
Account_ID  ACC101385
Name            Priya
                 1386
Account_ID  ACC101386
Name            Divya
                 1392
Account_ID  ACC101392
Name            Divya
                 1393
Account_ID  ACC101393
Name            Divya
                 1394
Account_ID  ACC101394
Name            Divya
                 1395
Account_ID  ACC101395
Name             Arun
                 1397
Account_ID  ACC101397
Name            Aisha
                 1398
Account_ID  ACC101398
Name            Kumar
                 1400
Account_ID  ACC101400
Name           Robert
                 1401
Account_ID  ACC101401
Name           Fatima
                 1402
Account_ID  ACC101402
Name             Arun
                 1407
Account_ID  ACC101407
Name             John
                 1409
Account_ID  ACC101409
Name             Mani
                 1411
Account_ID  ACC101411
Name             Kavi
                 1412
Account_ID  ACC101412
Name             Mani
                 1413
Account_ID  ACC101413
Name            Kumar
                 1416
Account_ID  ACC101416
Name            Aisha
                 1421
Account_ID  ACC101421
Name            Divya
                 1428
Account_ID  ACC101428
Name           Robert
                 1435
Account_ID  ACC101435
Name            Divya
                 1436
Account_ID  ACC101436
Name             John
                 1438
Account_ID  ACC101438
Name            Kumar
                 1439
Account_ID  ACC101439
Name            Kumar
                 1441
Account_ID  ACC101441
Name             Kavi
                 1443
Account_ID  ACC101443
Name             Kavi
                 1445
Account_ID  ACC101445
Name            Divya
                 1449
Account_ID  ACC101449
Name            Priya
                 1450
Account_ID  ACC101450
Name             Mani
                 1455
Account_ID  ACC101455
Name            Kumar
                 1459
Account_ID  ACC101459
Name           Robert
                 1461
Account_ID  ACC101461
Name             John
                 1462
Account_ID  ACC101462
Name            Kumar
                 1464
Account_ID  ACC101464
Name            Divya
                 1468
Account_ID  ACC101468
Name            Aisha
                 1473
Account_ID  ACC101473
Name           Robert
                 1474
Account_ID  ACC101474
Name           Fatima
                 1476
Account_ID  ACC101476
Name             Kavi
                 1477
Account_ID  ACC101477
Name            Kumar
                 1478
Account_ID  ACC101478
Name           Fatima
                 1479
Account_ID  ACC101479
Name             Mani
                 1481
Account_ID  ACC101481
Name             Kavi
                 1483
Account_ID  ACC101483
Name           Robert
                 1485
Account_ID  ACC101485
Name           Fatima
                 1486
Account_ID  ACC101486
Name            Priya
                 1488
Account_ID  ACC101488
Name            Priya
                 1491
Account_ID  ACC101491
Name             John
                 1492
Account_ID  ACC101492
Name           Fatima
                 1493
Account_ID  ACC101493
Name            Priya
                 1495
Account_ID  ACC101495
Name             Mani
                 1496
Account_ID  ACC101496
Name             Mani
                 1498
Account_ID  ACC101498
Name             John
                 1500
Account_ID  ACC101500
Name            Kumar
                 1501
Account_ID  ACC101501
Name           Robert
                 1505
Account_ID  ACC101505
Name            Kumar
                 1508
Account_ID  ACC101508
Name           Robert
                 1510
Account_ID  ACC101510
Name           Fatima
                 1511
Account_ID  ACC101511
Name            Priya
                 1519
Account_ID  ACC101519
Name             Mani
                 1520
Account_ID  ACC101520
Name             Kavi
                 1522
Account_ID  ACC101522
Name            Divya
                 1526
Account_ID  ACC101526
Name            Divya
                 1528
Account_ID  ACC101528
Name             Arun
                 1529
Account_ID  ACC101529
Name             Kavi
                 1531
Account_ID  ACC101531
Name             John
                 1533
Account_ID  ACC101533
Name             Arun
                 1541
Account_ID  ACC101541
Name            Priya
                 1544
Account_ID  ACC101544
Name             Arun
                 1547
Account_ID  ACC101547
Name            Kumar
                 1550
Account_ID  ACC101550
Name             John
                 1552
Account_ID  ACC101552
Name           Robert
                 1554
Account_ID  ACC101554
Name             John
                 1555
Account_ID  ACC101555
Name            Priya
                 1557
Account_ID  ACC101557
Name            Priya
                 1559
Account_ID  ACC101559
Name            Kumar
                 1562
Account_ID  ACC101562
Name           Fatima
                 1565
Account_ID  ACC101565
Name            Divya
                 1566
Account_ID  ACC101566
Name             Kavi
                 1567
Account_ID  ACC101567
Name            Priya
                 1568
Account_ID  ACC101568
Name             Kavi
                 1571
Account_ID  ACC101571
Name             John
                 1573
Account_ID  ACC101573
Name             Mani
                 1576
Account_ID  ACC101576
Name             Kavi
                 1577
Account_ID  ACC101577
Name            Aisha
                 1580
Account_ID  ACC101580
Name            Aisha
                 1587
Account_ID  ACC101587
Name            Divya
                 1588
Account_ID  ACC101588
Name           Fatima
                 1589
Account_ID  ACC101589
Name           Robert
                 1590
Account_ID  ACC101590
Name            Kumar
                 1591
Account_ID  ACC101591
Name             Mani
                 1593
Account_ID  ACC101593
Name           Fatima
                 1595
Account_ID  ACC101595
Name            Priya
                 1596
Account_ID  ACC101596
Name             Mani
                 1598
Account_ID  ACC101598
Name             Mani
                 1600
Account_ID  ACC101600
Name             Mani
                 1603
Account_ID  AC-101603
Name            Divya
                 1605
Account_ID  ACC101605
Name            Priya
                 1609
Account_ID  ACC101609
Name            Aisha
                 1611
Account_ID  ACC101611
Name            Kumar
                 1613
Account_ID  ACC101613
Name             Mani
                 1614
Account_ID  ACC101614
Name             Kavi
                 1615
Account_ID  ACC101615
Name            Kumar
                 1616
Account_ID  ACC101616
Name             Arun
                 1618
Account_ID  ACC101618
Name            Divya
                 1622
Account_ID  ACC101622
Name           Robert
                 1624
Account_ID  ACC101624
Name            Divya
                 1626
Account_ID  ACC101626
Name            Priya
                 1627
Account_ID  ACC101627
Name             Kavi
                 1628
Account_ID  ACC101628
Name             Mani
                 1629
Account_ID  ACC101629
Name             John
                 1630
Account_ID  ACC101630
Name             John
                 1631
Account_ID  ACC101631
Name            Kumar
                 1632
Account_ID  ACC101632
Name             Mani
                 1635
Account_ID  ACC101635
Name             John
                 1640
Account_ID  ACC101640
Name           Fatima
                 1643
Account_ID  ACC101643
Name            Divya
                 1645
Account_ID  ACC101645
Name             John
                 1646
Account_ID  ACC101646
Name             Mani
                 1651
Account_ID  ACC101651
Name            Divya
                 1652
Account_ID  ACC101652
Name             John
                 1657
Account_ID  ACC101657
Name           Robert
                 1659
Account_ID  ACC101659
Name             Mani
                 1660
Account_ID  ACC101660
Name             John
                 1663
Account_ID  ACC101663
Name            Priya
                 1664
Account_ID  ACC101664
Name           Robert
                 1666
Account_ID  ACC101666
Name            Divya
                 1667
Account_ID  ACC101667
Name            Priya
                 1668
Account_ID  ACC101668
Name             Arun
                 1675
Account_ID  ACC101675
Name            Priya
                 1679
Account_ID  ACC101679
Name            Aisha
                 1681
Account_ID  ACC101681
Name           Robert
                 1682
Account_ID  ACC101682
Name            Priya
                 1683
Account_ID  ACC101683
Name            Divya
                 1686
Account_ID  ACC101686
Name             Kavi
                 1687
Account_ID  ACC101687
Name             John
                 1688
Account_ID  ACC101688
Name            Priya
                 1689
Account_ID  ACC101689
Name             John
                 1692
Account_ID  ACC101692
Name             Arun
                 1693
Account_ID  ACC101693
Name             Mani
                 1694
Account_ID  ACC101694
Name           Robert
                 1696
Account_ID  ACC101696
Name           Fatima
                 1697
Account_ID  ACC101697
Name            Kumar
                 1700
Account_ID  ACC101700
Name             Mani
                 1702
Account_ID  ACC101702
Name           Robert
                 1704
Account_ID  ACC101704
Name             John
                 1705
Account_ID  ACC101705
Name             John
                 1706
Account_ID  ACC101706
Name            Aisha
                 1710
Account_ID  ACC101710
Name           Robert
                 1712
Account_ID  ACC101712
Name             Arun
                 1714
Account_ID  ACC101714
Name             Arun
                 1716
Account_ID  ACC101716
Name             Kavi
                 1721
Account_ID  ACC101721
Name             John
                 1722
Account_ID  ACC101722
Name            Kumar
                 1727
Account_ID  ACC101727
Name            Priya
                 1729
Account_ID  ACC101729
Name             Kavi
                 1731
Account_ID  ACC101731
Name           Robert
                 1732
Account_ID  ACC101732
Name           Robert
                 1738
Account_ID  ACC101738
Name             John
                 1741
Account_ID  ACC101741
Name            Kumar
                 1742
Account_ID  ACC101742
Name           Robert
                 1745
Account_ID  ACC101745
Name            Aisha
                 1746
Account_ID  ACC101746
Name           Fatima
                 1749
Account_ID  ACC101749
Name            Aisha
                 1751

3.	Fetch customers who opened accounts after 2020.

In [ ]:
df['Account_Open_Date']=pd.to_datetime(df['Account_Open_Date'],format='mixed')
df['Account_Open_Date']=df['Account_Open_Date'].dt.strftime('%d-%m-%y')

In [ ]:
df[df['Account_Open_Date'] > '01-01-2020']

,Account_ID,Account_Number,Name,Account_Type,Balance,Fixed_Deposit,Recurring_Deposit,Loan_Amount,Interest_Rate,Branch,City,Country,Email,Phone_Number,Transaction_Type,Withdrawal,Deposit,Transaction_Date,Account_Open_Date,Notes
0,ACC100000,9839401802,Divya,FD,1642743.0,60263,16023,100268.0,10,Delhi,Mumbai,UAE,divya@gmail.com,0000000000,Credit,157892,4886,17-07-24,24-10-22,Remove
1,ACC100001,7548779029,Aisha,Current,2417439.0,25658,18942,781743.0,12,Hyderabad,New York,Unites States,aisha@gmail.com,2638242648.0,DEBIT,53355,185796,09-01-21,23-08-16,Remove
3,ACC100003,9970006983,Robert,Savings,2249435.0,89789,24276,186769.0,14,Chennai,NaN,Unites States,robert@gmail.com,4798808687.0,DBT,-12935,173165,19-05-22,02-04-19,NaN
5,ACC100005,5404141609,John,RD,4328368.0,50015,41523,204020.0,10,Delhi,NaN,India,john@gmail.com,4663625198.0,Credit,48806,87982,06-03-17,17-11-17,NaN
6,ACC100006,5819331062,Kavi,Savings,4344539.0,23776,30080,15939.0,16,Delhi,Mumbai,India,kavi@gmail.com,3826578402.0,credit,129997,124013,25-10-16,21-06-20,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4991,ACC104991,4468637158,Aisha,Current,3775023.0,46673,19072,1393603.0,16,Hyderabad,Mumbai,Unites States,aisha@gmail.com,7438506973.0,credit,45879,44369,05-04-20,08-12-17,NaN
4992,ACC104992,7462281200,Divya,FD,2417439.0,50883,3588,1171066.0,8,Chennai,NaN,India,divya@gmail.com,1144081617.0,Credit,136329,28745,11-02-17,12-12-20,Check
4995,ACC104995,1905811747,Divya,RD,4254142.0,26651,4944,556284.0,16,Chennai,Dubai,India,divya@gmail.com,1322206462.0,Credit,176191,103276,16-06-23,26-10-23,Temp
4996,ACC104996,3314293638,Robert,Current,2417439.0,42556,8389,224232.0,12,Delhi,Dubai,UAE,robert@gmail.com,3457287846.0,DBT,70113,180296,05-04-20,15-07-16,NaN
4997,ACC104997,5875650079,Arun,Savings,4579182.0,85525,49965,325034.0,16,Bangalore,Mumbai,Unites States,arun@gmail.com,8212358188.0,DBT,57986,96335,24-05-18,14-12-21,Temp

4.	Fetch all “Current Account” holders.

In [ ]:
for i in df.index:
  if df.loc[i,'Account_Type'] == 'Current':
    print(pd.DataFrame(df.loc[i,['Name','Account_ID']]))

                    1
Name            Aisha
Account_ID  ACC100001
                    9
Name            Kumar
Account_ID  ACC100009
                   15
Name           Fatima
Account_ID  ACC100015
                   22
Name             John
Account_ID  ACC100022
                   25
Name             John
Account_ID  ACC100025
                   29
Name             John
Account_ID  ACC100029
                   34
Name            Divya
Account_ID  ACC100034
                   35
Name             Arun
Account_ID  ACC100035
                   48
Name            Aisha
Account_ID  ACC100048
                   51
Name            Kumar
Account_ID  ACC100051
                   65
Name             Mani
Account_ID  ACC100065
                   72
Name            Divya
Account_ID  ACC100072
                   73
Name            Priya
Account_ID  ACC100073
                   77
Name            Priya
Account_ID  ACC100077
                   87
Name             Arun
Account_ID  ACC100087
                   95
Name            Divya
Account_ID  AC-100095
                   98
Name           Fatima
Account_ID  ACC100098
                  110
Name           Robert
Account_ID  ACC100110
                  117
Name            Priya
Account_ID  ACC100117
                  118
Name            Divya
Account_ID  ACC100118
                  121
Name            Divya
Account_ID  ACC100121
                  134
Name            Priya
Account_ID  ACC100134
                  138
Name            Aisha
Account_ID  ACC100138
                  139
Name             John
Account_ID  ACC100139
                  141
Name             Mani
Account_ID  ACC100141
                  148
Name           Fatima
Account_ID  ACC100148
                  153
Name           Fatima
Account_ID  ACC100153
                  155
Name             Kavi
Account_ID  ACC100155
                  158
Name            Priya
Account_ID  ACC100158
                  169
Name            Divya
Account_ID  AC-100169
                  185
Name           Robert
Account_ID  ACC100185
                  199
Name             Kavi
Account_ID  ACC100199
                  204
Name             Kavi
Account_ID  ACC100204
                  214
Name             John
Account_ID  ACC100214
                  217
Name            Kumar
Account_ID  ACC100217
                  222
Name             Arun
Account_ID  ACC100222
                  230
Name             Mani
Account_ID  ACC100230
                  251
Name             Kavi
Account_ID  ACC100251
                  253
Name            Divya
Account_ID  ACC100253
                  256
Name           Robert
Account_ID  ACC100256
                  260
Name            Priya
Account_ID  ACC100260
                  280
Name            Divya
Account_ID  ACC100280
                  282
Name           Fatima
Account_ID  ACC100282
                  286
Name            Aisha
Account_ID  ACC100286
                  290
Name            Divya
Account_ID  ACC100290
                  296
Name            Divya
Account_ID  AC-100296
                  302
Name           Fatima
Account_ID  ACC100302
                  304
Name            Kumar
Account_ID  ACC100304
                  306
Name            Kumar
Account_ID  ACC100306
                  308
Name             Mani
Account_ID  ACC100308
                  323
Name             John
Account_ID  ACC100323
                  326
Name             Mani
Account_ID  ACC100326
                  334
Name            Divya
Account_ID  ACC100334
                  338
Name             Kavi
Account_ID  ACC100338
                  345
Name            Divya
Account_ID  AC-100345
                  355
Name             Kavi
Account_ID  ACC100355
                  356
Name            Priya
Account_ID  ACC100356
                  360
Name             Kavi
Account_ID  ACC100360
                  372
Name            Aisha
Account_ID  ACC100372
                  412
Name             Arun
Account_ID  ACC100412
                  420
Name             Kavi
Account_ID  ACC100420
                  422
Name             Mani
Account_ID  ACC100422
                  424
Name            Divya
Account_ID  ACC100424
                  426
Name            Priya
Account_ID  ACC100426
                  432
Name             John
Account_ID  ACC100432
                  434
Name            Kumar
Account_ID  ACC100434
                  447
Name           Fatima
Account_ID  ACC100447
                  451
Name             John
Account_ID  ACC100451
                  462
Name            Divya
Account_ID  ACC100462
                  463
Name            Priya
Account_ID  AC-100463
                  468
Name           Fatima
Account_ID  ACC100468
                  483
Name            Kumar
Account_ID  ACC100483
                  492
Name             Mani
Account_ID  ACC100492
                  493
Name           Fatima
Account_ID  ACC100493
                  498
Name           Robert
Account_ID  ACC100498
                  499
Name             Mani
Account_ID  ACC100499
                  504
Name             John
Account_ID  ACC100504
                  507
Name            Priya
Account_ID  ACC100507
                  510
Name            Priya
Account_ID  ACC100510
                  517
Name             Arun
Account_ID  ACC100517
                  528
Name             Mani
Account_ID  ACC100528
                  536
Name            Kumar
Account_ID  ACC100536
                  550
Name             Kavi
Account_ID  AC-100550
                  551
Name             Arun
Account_ID  ACC100551
                  553
Name            Divya
Account_ID  ACC100553
                  560
Name            Aisha
Account_ID  ACC100560
                  564
Name            Aisha
Account_ID  ACC100564
                  578
Name            Aisha
Account_ID  ACC100578
                  580
Name            Divya
Account_ID  ACC100580
                  584
Name             John
Account_ID  ACC100584
                  587
Name             Kavi
Account_ID  ACC100587
                  596
Name             Arun
Account_ID  ACC100596
                  599
Name           Fatima
Account_ID  ACC100599
                  620
Name             Kavi
Account_ID  ACC100620
                  623
Name             Kavi
Account_ID  ACC100623
                  628
Name           Fatima
Account_ID  ACC100628
                  632
Name           Robert
Account_ID  ACC100632
                  637
Name            Divya
Account_ID  ACC100637
                  642
Name           Robert
Account_ID  ACC100642
                  646
Name           Fatima
Account_ID  ACC100646
                  648
Name            Divya
Account_ID  ACC100648
                  649
Name            Priya
Account_ID  ACC100649
                  650
Name            Kumar
Account_ID  ACC100650
                  653
Name           Fatima
Account_ID  ACC100653
                  655
Name           Robert
Account_ID  ACC100655
                  659
Name           Robert
Account_ID  ACC100659
                  665
Name            Kumar
Account_ID  ACC100665
                  668
Name            Kumar
Account_ID  ACC100668
                  681
Name           Robert
Account_ID  ACC100681
                  687
Name             Mani
Account_ID  ACC100687
                  690
Name            Divya
Account_ID  ACC100690
                  692
Name             Arun
Account_ID  ACC100692
                  695
Name            Divya
Account_ID  ACC100695
                  699
Name            Kumar
Account_ID  ACC100699
                  700
Name            Aisha
Account_ID  ACC100700
                  704
Name           Fatima
Account_ID  ACC100704
                  708
Name            Divya
Account_ID  ACC100708
                  709
Name             Arun
Account_ID  ACC100709
                  711
Name            Aisha
Account_ID  ACC100711
                  718
Name             John
Account_ID  ACC100718
                  723
Name            Divya
Account_ID  ACC100723
                  731
Name            Divya
Account_ID  ACC100731
                  745
Name           Fatima
Account_ID  ACC100745
                  748
Name             Arun
Account_ID  ACC100748
                  751
Name            Kumar
Account_ID  ACC100751
                  752
Name             Kavi
Account_ID  ACC100752
                  756
Name            Priya
Account_ID  ACC100756
                  766
Name             Kavi
Account_ID  ACC100766
                  771
Name            Kumar
Account_ID  ACC100771
                  772
Name             John
Account_ID  ACC100772
                  773
Name             Arun
Account_ID  ACC100773
                  777
Name             Kavi
Account_ID  ACC100777
                  779
Name             John
Account_ID  ACC100779
                  783
Name             Kavi
Account_ID  ACC100783
                  787
Name            Divya
Account_ID  ACC100787
                  791
Name            Aisha
Account_ID  ACC100791
                  795
Name            Aisha
Account_ID  ACC100795
                  798
Name            Divya
Account_ID  ACC100798
                  800
Name            Aisha
Account_ID  ACC100800
                  801
Name             Arun
Account_ID  ACC100801
                  806
Name            Priya
Account_ID  ACC100806
                  808
Name            Kumar
Account_ID  ACC100808
                  811
Name             Arun
Account_ID  ACC100811
                  814
Name             Kavi
Account_ID  ACC100814
                  817
Name             Mani
Account_ID  ACC100817
                  819
Name             Kavi
Account_ID  ACC100819
                  820
Name            Kumar
Account_ID  ACC100820
                  826
Name             Arun
Account_ID  ACC100826
                  832
Name           Robert
Account_ID  ACC100832
                  833
Name             John
Account_ID  ACC100833
                  837
Name           Fatima
Account_ID  ACC100837
                  839
Name             Mani
Account_ID  ACC100839
                  844
Name            Kumar
Account_ID  ACC100844
                  847
Name           Robert
Account_ID  ACC100847
                  858
Name            Kumar
Account_ID  AC-100858
                  860
Name             Arun
Account_ID  ACC100860
                  864
Name             Kavi
Account_ID  ACC100864
                  873
Name           Robert
Account_ID  ACC100873
                  875
Name            Kumar
Account_ID  ACC100875
                  883
Name            Kumar
Account_ID  ACC100883
                  888
Name             Kavi
Account_ID  ACC100888
                  889
Name            Aisha
Account_ID  ACC100889
                  895
Name             Mani
Account_ID  ACC100895
                  899
Name             John
Account_ID  ACC100899
                  900
Name             Arun
Account_ID  ACC100900
                  906
Name             John
Account_ID  ACC100906
                  914
Name             Arun
Account_ID  ACC100914
                  915
Name           Fatima
Account_ID  ACC100915
                  917
Name            Aisha
Account_ID  ACC100917
                  919
Name             Mani
Account_ID  ACC100919
                  920
Name            Divya
Account_ID  ACC100920
                  928
Name           Fatima
Account_ID  ACC100928
                  932
Name             John
Account_ID  ACC100932
                  945
Name             Kavi
Account_ID  ACC100945
                  947
Name             John
Account_ID  ACC100947
                  956
Name            Aisha
Account_ID  ACC100956
                  960
Name            Aisha
Account_ID  ACC100960
                  961
Name             Mani
Account_ID  ACC100961
                  964
Name            Divya
Account_ID  ACC100964
                  967
Name            Aisha
Account_ID  ACC100967
                  969
Name           Robert
Account_ID  ACC100969
                  976
Name            Priya
Account_ID  ACC100976
                  979
Name             Mani
Account_ID  ACC100979
                  980
Name           Robert
Account_ID  ACC100980
                  983
Name             Kavi
Account_ID  ACC100983
                  987
Name             Mani
Account_ID  ACC100987
                  992
Name            Priya
Account_ID  ACC100992
                  993
Name            Divya
Account_ID  ACC100993
                  995
Name             Arun
Account_ID  ACC100995
                  996
Name           Robert
Account_ID  AC-100996
                 1000
Name           Robert
Account_ID  ACC101000
                 1008
Name             Arun
Account_ID  ACC101008
                 1009
Name             Arun
Account_ID  ACC101009
                 1014
Name            Aisha
Account_ID  ACC101014
                 1020
Name             Arun
Account_ID  ACC101020
                 1024
Name           Robert
Account_ID  ACC101024
                 1029
Name            Aisha
Account_ID  ACC101029
                 1031
Name            Kumar
Account_ID  ACC101031
                 1037
Name            Kumar
Account_ID  ACC101037
                 1038
Name            Divya
Account_ID  ACC101038
                 1064
Name             Mani
Account_ID  ACC101064
                 1065
Name           Robert
Account_ID  ACC101065
                 1066
Name           Robert
Account_ID  ACC101066
                 1070
Name             Mani
Account_ID  ACC101070
                 1077
Name            Kumar
Account_ID  ACC101077
                 1080
Name            Divya
Account_ID  ACC101080
                 1082
Name            Divya
Account_ID  ACC101082
                 1093
Name            Priya
Account_ID  ACC101093
                 1095
Name            Aisha
Account_ID  ACC101095
                 1106
Name            Priya
Account_ID  ACC101106
                 1113
Name             Arun
Account_ID  ACC101113
                 1114
Name           Fatima
Account_ID  ACC101114
                 1115
Name             Arun
Account_ID  ACC101115
                 1117
Name             Kavi
Account_ID  ACC101117
                 1124
Name            Kumar
Account_ID  ACC101124
                 1156
Name           Robert
Account_ID  ACC101156
                 1160
Name             Mani
Account_ID  ACC101160
                 1161
Name           Fatima
Account_ID  ACC101161
                 1162
Name            Priya
Account_ID  ACC101162
                 1182
Name           Robert
Account_ID  ACC101182
                 1188
Name            Aisha
Account_ID  ACC101188
                 1190
Name            Divya
Account_ID  ACC101190
                 1194
Name            Divya
Account_ID  ACC101194
                 1195
Name             John
Account_ID  ACC101195
                 1206
Name            Kumar
Account_ID  ACC101206
                 1212
Name            Priya
Account_ID  ACC101212
                 1213
Name             John
Account_ID  ACC101213
                 1215
Name            Kumar
Account_ID  ACC101215
                 1218
Name             Kavi
Account_ID  ACC101218
                 1223
Name             Mani
Account_ID  ACC101223
                 1224
Name            Priya
Account_ID  ACC101224
                 1226
Name             Kavi
Account_ID  ACC101226
                 1231
Name           Robert
Account_ID  ACC101231
                 1232
Name             Mani
Account_ID  ACC101232
                 1233
Name           Robert
Account_ID  ACC101233
                 1247
Name           Robert
Account_ID  ACC101247
                 1248
Name             Arun
Account_ID  AC-101248
                 1253
Name            Kumar
Account_ID  ACC101253
                 1256
Name             John
Account_ID  ACC101256
                 1265
Name           Fatima
Account_ID  ACC101265
                 1269
Name            Aisha
Account_ID  ACC101269
                 1276
Name             John
Account_ID  ACC101276
                 1277
Name            Aisha
Account_ID  ACC101277
                 1287
Name            Aisha
Account_ID  ACC101287
                 1289
Name            Aisha
Account_ID  ACC101289
                 1295
Name             John
Account_ID  ACC101295
                 1296
Name            Aisha
Account_ID  ACC101296
                 1301
Name             Arun
Account_ID  ACC101301
                 1313
Name             John
Account_ID  ACC101313
                 1321
Name            Priya
Account_ID  ACC101321
                 1322
Name           Robert
Account_ID  ACC101322
                 1328
Name             Arun
Account_ID  ACC101328
                 1334
Name           Fatima
Account_ID  ACC101334
                 1338
Name           Fatima
Account_ID  ACC101338
                 1341
Name           Robert
Account_ID  ACC101341
                 1345
Name             Kavi
Account_ID  ACC101345
                 1356
Name             John
Account_ID  ACC101356
                 1359
Name            Divya
Account_ID  ACC101359
                 1365
Name           Fatima
Account_ID  ACC101365
                 1370
Name             Kavi
Account_ID  ACC101370
                 1371
Name            Aisha
Account_ID  ACC101371
                 1373
Name             John
Account_ID  ACC101373
                 1376
Name            Kumar
Account_ID  ACC101376
                 1384
Name             Arun
Account_ID  ACC101384
                 1388
Name             John
Account_ID  ACC101388
                 1393
Name            Divya
Account_ID  ACC101393
                 1398
Name            Kumar
Account_ID  ACC101398
                 1401
Name           Fatima
Account_ID  ACC101401
                 1404
Name             Mani
Account_ID  ACC101404
                 1421
Name            Divya
Account_ID  ACC101421
                 1424
Name             Arun
Account_ID  ACC101424
                 1428
Name           Robert
Account_ID  ACC101428
                 1429
Name            Aisha
Account_ID  ACC101429
                 1434
Name           Robert
Account_ID  ACC101434
                 1439
Name            Kumar
Account_ID  ACC101439
                 1444
Name           Fatima
Account_ID  AC-101444
                 1460
Name           Fatima
Account_ID  ACC101460
                 1461
Name             John
Account_ID  ACC101461
                 1474
Name           Fatima
Account_ID  ACC101474
                 1475
Name            Kumar
Account_ID  ACC101475
                 1483
Name           Robert
Account_ID  ACC101483
                 1501
Name           Robert
Account_ID  ACC101501
                 1503
Name            Priya
Account_ID  ACC101503
                 1505
Name            Kumar
Account_ID  ACC101505
                 1508
Name           Robert
Account_ID  ACC101508
                 1510
Name           Fatima
Account_ID  ACC101510
                 1520
Name             Kavi
Account_ID  ACC101520
                 1527
Name             Mani
Account_ID  ACC101527
                 1528
Name             Arun
Account_ID  ACC101528
                 1529
Name             Kavi
Account_ID  ACC101529
                 1533
Name             Arun
Account_ID  ACC101533
                 1549
Name            Aisha
Account_ID  ACC101549
                 1550
Name             John
Account_ID  ACC101550
                 1560
Name             Arun
Account_ID  ACC101560
                 1572
Name            Aisha
Account_ID  ACC101572
                 1573
Name             Mani
Account_ID  ACC101573
                 1576
Name             Kavi
Account_ID  ACC101576
                 1579
Name            Aisha
Account_ID  ACC101579
                 1582
Name           Robert
Account_ID  ACC101582
                 1591
Name             Mani
Account_ID  ACC101591
                 1595
Name            Priya
Account_ID  ACC101595
                 1609
Name            Aisha
Account_ID  ACC101609
                 1627
Name             Kavi
Account_ID  ACC101627

5.	Fetch all accounts where Email is missing or invalid.

In [ ]:
if i in df.index:
  if '@' not in df.loc[i,'Email']:
    print(df.loc[i])
  print('no Missing or invalid Email')

no Missing or invalid Email

6.	Fetch customers whose Country = “India”.

In [ ]:

for i in df.index:
  if df.loc[i,'Country']=='India':
      print(pd.DataFrame(df.loc[i,['Name','Account_ID','Country']]))

                    5
Name             John
Account_ID  ACC100005
Country         India
                    6
Name             Kavi
Account_ID  ACC100006
Country         India
                    9
Name            Kumar
Account_ID  ACC100009
Country         India
                   19
Name            Aisha
Account_ID  ACC100019
Country         India
                   21
Name             Mani
Account_ID  ACC100021
Country         India
                   22
Name             John
Account_ID  ACC100022
Country         India
                   29
Name             John
Account_ID  ACC100029
Country         India
                   35
Name             Arun
Account_ID  ACC100035
Country         India
                   37
Name            Divya
Account_ID  ACC100037
Country         India
                   38
Name            Divya
Account_ID  ACC100038
Country         India
                   46
Name           Fatima
Account_ID  ACC100046
Country         India
                   49
Name             Arun
Account_ID  ACC100049
Country         India
                   54
Name             Kavi
Account_ID  ACC100054
Country         India
                   72
Name            Divya
Account_ID  ACC100072
Country         India
                   73
Name            Priya
Account_ID  ACC100073
Country         India
                   74
Name             Kavi
Account_ID  ACC100074
Country         India
                   78
Name            Aisha
Account_ID  ACC100078
Country         India
                   81
Name           Robert
Account_ID  ACC100081
Country         India
                   83
Name             John
Account_ID  ACC100083
Country         India
                   99
Name           Robert
Account_ID  ACC100099
Country         India
                  101
Name            Divya
Account_ID  ACC100101
Country         India
                  114
Name            Priya
Account_ID  ACC100114
Country         India
                  123
Name             Mani
Account_ID  ACC100123
Country         India
                  126
Name             Mani
Account_ID  ACC100126
Country         India
                  128
Name            Aisha
Account_ID  ACC100128
Country         India
                  130
Name             John
Account_ID  AC-100130
Country         India
                  133
Name             Kavi
Account_ID  ACC100133
Country         India
                  135
Name            Kumar
Account_ID  ACC100135
Country         India
                  138
Name            Aisha
Account_ID  ACC100138
Country         India
                  141
Name             Mani
Account_ID  ACC100141
Country         India
                  144
Name            Priya
Account_ID  ACC100144
Country         India
                  147
Name             Mani
Account_ID  ACC100147
Country         India
                  151
Name            Divya
Account_ID  ACC100151
Country         India
                  152
Name            Aisha
Account_ID  ACC100152
Country         India
                  158
Name            Priya
Account_ID  ACC100158
Country         India
                  159
Name            Kumar
Account_ID  ACC100159
Country         India
                  178
Name             Arun
Account_ID  ACC100178
Country         India
                  181
Name           Robert
Account_ID  ACC100181
Country         India
                  185
Name           Robert
Account_ID  ACC100185
Country         India
                  188
Name             Kavi
Account_ID  ACC100188
Country         India
                  190
Name            Aisha
Account_ID  ACC100190
Country         India
                  191
Name            Priya
Account_ID  ACC100191
Country         India
                  193
Name            Kumar
Account_ID  ACC100193
Country         India
                  195
Name            Priya
Account_ID  ACC100195
Country         India
                  197
Name             Kavi
Account_ID  ACC100197
Country         India
                  202
Name            Priya
Account_ID  ACC100202
Country         India
                  206
Name           Fatima
Account_ID  ACC100206
Country         India
                  213
Name           Robert
Account_ID  ACC100213
Country         India
                  216
Name            Kumar
Account_ID  ACC100216
Country         India
                  227
Name             John
Account_ID  ACC100227
Country         India
                  233
Name             John
Account_ID  ACC100233
Country         India
                  240
Name             Mani
Account_ID  ACC100240
Country         India
                  254
Name            Kumar
Account_ID  ACC100254
Country         India
                  260
Name            Priya
Account_ID  ACC100260
Country         India
                  263
Name            Priya
Account_ID  ACC100263
Country         India
                  264
Name           Fatima
Account_ID  ACC100264
Country         India
                  267
Name           Fatima
Account_ID  ACC100267
Country         India
                  269
Name             Mani
Account_ID  ACC100269
Country         India
                  270
Name            Kumar
Account_ID  ACC100270
Country         India
                  278
Name           Fatima
Account_ID  ACC100278
Country         India
                  281
Name            Kumar
Account_ID  ACC100281
Country         India
                  282
Name           Fatima
Account_ID  ACC100282
Country         India
                  286
Name            Aisha
Account_ID  ACC100286
Country         India
                  288
Name           Robert
Account_ID  ACC100288
Country         India
                  290
Name            Divya
Account_ID  ACC100290
Country         India
                  296
Name            Divya
Account_ID  AC-100296
Country         India
                  299
Name             John
Account_ID  ACC100299
Country         India
                  300
Name            Priya
Account_ID  ACC100300
Country         India
                  304
Name            Kumar
Account_ID  ACC100304
Country         India
                  315
Name             Kavi
Account_ID  ACC100315
Country         India
                  317
Name           Robert
Account_ID  ACC100317
Country         India
                  325
Name             Arun
Account_ID  ACC100325
Country         India
                  326
Name             Mani
Account_ID  ACC100326
Country         India
                  330
Name           Robert
Account_ID  ACC100330
Country         India
                  333
Name            Divya
Account_ID  ACC100333
Country         India
                  334
Name            Divya
Account_ID  ACC100334
Country         India
                  336
Name           Fatima
Account_ID  ACC100336
Country         India
                  341
Name            Priya
Account_ID  ACC100341
Country         India
                  349
Name           Fatima
Account_ID  ACC100349
Country         India
                  352
Name             Arun
Account_ID  ACC100352
Country         India
                  357
Name            Divya
Account_ID  ACC100357
Country         India
                  359
Name             Arun
Account_ID  ACC100359
Country         India
                  360
Name             Kavi
Account_ID  ACC100360
Country         India
                  373
Name            Divya
Account_ID  ACC100373
Country         India
                  376
Name             Arun
Account_ID  AC-100376
Country         India
                  381
Name           Robert
Account_ID  ACC100381
Country         India
                  394
Name             Kavi
Account_ID  ACC100394
Country         India
                  410
Name             John
Account_ID  ACC100410
Country         India
                  415
Name            Priya
Account_ID  ACC100415
Country         India
                  422
Name             Mani
Account_ID  ACC100422
Country         India
                  426
Name            Priya
Account_ID  ACC100426
Country         India
                  432
Name             John
Account_ID  ACC100432
Country         India
                  436
Name             John
Account_ID  ACC100436
Country         India
                  440
Name            Aisha
Account_ID  ACC100440
Country         India
                  462
Name            Divya
Account_ID  ACC100462
Country         India
                  476
Name             John
Account_ID  AC-100476
Country         India
                  480
Name             Arun
Account_ID  ACC100480
Country         India
                  488
Name             John
Account_ID  ACC100488
Country         India
                  491
Name           Robert
Account_ID  ACC100491
Country         India
                  492
Name             Mani
Account_ID  ACC100492
Country         India
                  498
Name           Robert
Account_ID  ACC100498
Country         India
                  499
Name             Mani
Account_ID  ACC100499
Country         India
                  504
Name             John
Account_ID  ACC100504
Country         India
                  514
Name           Robert
Account_ID  ACC100514
Country         India
                  518
Name             Kavi
Account_ID  AC-100518
Country         India
                  522
Name            Divya
Account_ID  ACC100522
Country         India
                  525
Name            Divya
Account_ID  ACC100525
Country         India
                  530
Name           Robert
Account_ID  ACC100530
Country         India
                  532
Name            Divya
Account_ID  ACC100532
Country         India
                  536
Name            Kumar
Account_ID  ACC100536
Country         India
                  544
Name           Fatima
Account_ID  ACC100544
Country         India
                  546
Name           Fatima
Account_ID  ACC100546
Country         India
                  560
Name            Aisha
Account_ID  ACC100560
Country         India
                  563
Name            Aisha
Account_ID  ACC100563
Country         India
                  564
Name            Aisha
Account_ID  ACC100564
Country         India
                  572
Name             John
Account_ID  ACC100572
Country         India
                  575
Name            Divya
Account_ID  ACC100575
Country         India
                  595
Name            Kumar
Account_ID  ACC100595
Country         India
                  602
Name             Arun
Account_ID  ACC100602
Country         India
                  613
Name            Kumar
Account_ID  ACC100613
Country         India
                  615
Name            Priya
Account_ID  ACC100615
Country         India
                  616
Name             Arun
Account_ID  ACC100616
Country         India
                  617
Name           Fatima
Account_ID  ACC100617
Country         India
                  618
Name             Kavi
Account_ID  ACC100618
Country         India
                  619
Name            Kumar
Account_ID  ACC100619
Country         India
                  620
Name             Kavi
Account_ID  ACC100620
Country         India
                  642
Name           Robert
Account_ID  ACC100642
Country         India
                  649
Name            Priya
Account_ID  ACC100649
Country         India
                  655
Name           Robert
Account_ID  ACC100655
Country         India
                  660
Name             John
Account_ID  ACC100660
Country         India
                  665
Name            Kumar
Account_ID  ACC100665
Country         India
                  674
Name            Divya
Account_ID  ACC100674
Country         India
                  686
Name            Priya
Account_ID  ACC100686
Country         India
                  687
Name             Mani
Account_ID  ACC100687
Country         India
                  690
Name            Divya
Account_ID  ACC100690
Country         India
                  693
Name             John
Account_ID  ACC100693
Country         India
                  698
Name             Mani
Account_ID  ACC100698
Country         India
                  701
Name            Aisha
Account_ID  ACC100701
Country         India
                  704
Name           Fatima
Account_ID  ACC100704
Country         India
                  705
Name             Arun
Account_ID  AC-100705
Country         India
                  708
Name            Divya
Account_ID  ACC100708
Country         India
                  713
Name             Mani
Account_ID  ACC100713
Country         India
                  717
Name             Mani
Account_ID  ACC100717
Country         India
                  726
Name           Robert
Account_ID  ACC100726
Country         India
                  729
Name            Aisha
Account_ID  ACC100729
Country         India
                  737
Name             John
Account_ID  ACC100737
Country         India
                  742
Name            Kumar
Account_ID  ACC100742
Country         India
                  744
Name             Kavi
Account_ID  ACC100744
Country         India
                  747
Name            Kumar
Account_ID  ACC100747
Country         India
                  750
Name             Kavi
Account_ID  ACC100750
Country         India
                  757
Name            Priya
Account_ID  ACC100757
Country         India
                  765
Name             Kavi
Account_ID  ACC100765
Country         India
                  767
Name           Robert
Account_ID  ACC100767
Country         India
                  768
Name            Aisha
Account_ID  ACC100768
Country         India
                  769
Name           Robert
Account_ID  ACC100769
Country         India
                  773
Name             Arun
Account_ID  ACC100773
Country         India
                  774
Name           Robert
Account_ID  ACC100774
Country         India
                  784
Name             Mani
Account_ID  ACC100784
Country         India
                  787
Name            Divya
Account_ID  ACC100787
Country         India
                  788
Name            Divya
Account_ID  ACC100788
Country         India
                  791
Name            Aisha
Account_ID  ACC100791
Country         India
                  792
Name            Divya
Account_ID  ACC100792
Country         India
                  796
Name             Kavi
Account_ID  ACC100796
Country         India
                  798
Name            Divya
Account_ID  ACC100798
Country         India
                  801
Name             Arun
Account_ID  ACC100801
Country         India
                  802
Name             John
Account_ID  ACC100802
Country         India
                  804
Name            Aisha
Account_ID  ACC100804
Country         India
                  806
Name            Priya
Account_ID  ACC100806
Country         India
                  809
Name             Kavi
Account_ID  ACC100809
Country         India
                  814
Name             Kavi
Account_ID  ACC100814
Country         India
                  832
Name           Robert
Account_ID  ACC100832
Country         India
                  840
Name             John
Account_ID  ACC100840
Country         India
                  855
Name            Kumar
Account_ID  ACC100855
Country         India
                  864
Name             Kavi
Account_ID  ACC100864
Country         India
                  867
Name            Divya
Account_ID  ACC100867
Country         India
                  879
Name             John
Account_ID  ACC100879
Country         India
                  899
Name             John
Account_ID  ACC100899
Country         India
                  906
Name             John
Account_ID  ACC100906
Country         India
                  927
Name             Mani
Account_ID  ACC100927
Country         India
                  928
Name           Fatima
Account_ID  ACC100928
Country         India
                  932
Name             John
Account_ID  ACC100932
Country         India
                  942
Name            Priya
Account_ID  ACC100942
Country         India
                  947
Name             John
Account_ID  ACC100947
Country         India
                  952
Name            Kumar
Account_ID  ACC100952
Country         India
                  955
Name            Divya
Account_ID  ACC100955
Country         India
                  962
Name           Robert
Account_ID  ACC100962
Country         India
                  967
Name            Aisha
Account_ID  ACC100967
Country         India
                  974
Name             Mani
Account_ID  ACC100974
Country         India
                  978
Name             Mani
Account_ID  ACC100978
Country         India
                  980
Name           Robert
Account_ID  ACC100980
Country         India
                  982
Name             Mani
Account_ID  ACC100982
Country         India
                  986
Name             Arun
Account_ID  ACC100986
Country         India
                  993
Name            Divya
Account_ID  ACC100993
Country         India
                  995
Name             Arun
Account_ID  ACC100995
Country         India
                 1010
Name           Robert
Account_ID  ACC101010
Country         India
                 1026
Name            Priya
Account_ID  ACC101026
Country         India
                 1031
Name            Kumar
Account_ID  ACC101031
Country         India
                 1032
Name            Divya
Account_ID  ACC101032
Country         India
                 1033
Name             Arun
Account_ID  ACC101033
Country         India
                 1036
Name            Aisha
Account_ID  ACC101036
Country         India
                 1043
Name            Aisha
Account_ID  ACC101043
Country         India
                 1044
Name             Mani
Account_ID  ACC101044
Country         India
                 1048
Name           Fatima
Account_ID  ACC101048
Country         India
                 1061
Name            Priya
Account_ID  ACC101061
Country         India
                 1064
Name             Mani
Account_ID  ACC101064
Country         India
                 1072
Name            Kumar
Account_ID  ACC101072
Country         India
                 1073
Name             Arun
Account_ID  ACC101073
Country         India
                 1080
Name            Divya
Account_ID  ACC101080
Country         India
                 1088
Name            Aisha
Account_ID  ACC101088
Country         India
                 1095
Name            Aisha
Account_ID  ACC101095
Country         India
                 1109
Name            Aisha
Account_ID  ACC101109
Country         India
                 1110
Name           Robert
Account_ID  ACC101110
Country         India
                 1115
Name             Arun
Account_ID  ACC101115
Country         India
                 1125
Name             Arun
Account_ID  AC-101125
Country         India
                 1132
Name            Kumar
Account_ID  ACC101132
Country         India
                 1135
Name            Priya
Account_ID  ACC101135
Country         India
                 1150
Name            Kumar
Account_ID  ACC101150
Country         India
                 1153
Name           Robert
Account_ID  ACC101153
Country         India
                 1155
Name            Priya
Account_ID  ACC101155
Country         India
                 1156
Name           Robert
Account_ID  ACC101156
Country         India
                 1159
Name             Arun
Account_ID  ACC101159
Country         India
                 1173
Name            Divya
Account_ID  ACC101173
Country         India
                 1181
Name            Priya
Account_ID  ACC101181
Country         India
                 1187
Name            Aisha
Account_ID  ACC101187
Country         India
                 1192
Name            Priya
Account_ID  ACC101192
Country         India
                 1195
Name             John
Account_ID  ACC101195
Country         India
                 1199
Name            Divya
Account_ID  ACC101199
Country         India
                 1201

7.	Fetch customers with more than 3 transactions in a day.

In [ ]:
v=df['Account_ID'].value_counts()
for i in v.index:
  if (v[i] > 3) == True:
    print(i,v[i])
  #else:
    #print('no customer with more than 3 transactions in a day')

8.	Fetch accounts with minimum balance less than 500.

In [ ]:
for i in df.index:
   if df.loc[i,'Balance'] < 500 :
      print(pd.DataFrame(df.loc[i,['Name','Account_Number','Balance']]))

9.	Fetch customers with Loan_Interest_Rate > 12%.

In [ ]:
for i in df.index:
   if df.loc[i,'Interest_Rate'] < 12:
      print(pd.DataFrame(df.loc[i,['Name','Account_Number','Interest_Rate']]))

Streaming output truncated to the last 5000 lines.
                        15
Name                Fatima
Account_Number  4555670279
Interest_Rate           10
                        16
Name                  Arun
Account_Number  1744293433
Interest_Rate            8
                        21
Name                  Mani
Account_Number  9947638415
Interest_Rate           10
                        25
Name                  John
Account_Number  4930987466
Interest_Rate           10
                        29
Name                  John
Account_Number  3746036109
Interest_Rate           10
                        30
Name                  Mani
Account_Number  7961307397
Interest_Rate            8
                        34
Name                 Divya
Account_Number  7904397119
Interest_Rate            8
                        35
Name                  Arun
Account_Number  6402651504
Interest_Rate           10
                        37
Name                 Divya
Account_Number  4139051895
Interest_Rate           10
                        38
Name                 Divya
Account_Number  7541516185
Interest_Rate           10
                        39
Name                Fatima
Account_Number  3127828256
Interest_Rate           10
                        43
Name                  Mani
Account_Number  5440477172
Interest_Rate            8
                        44
Name                 Aisha
Account_Number  3684251440
Interest_Rate            8
                        49
Name                  Arun
Account_Number  7874167563
Interest_Rate           10
                        51
Name                 Kumar
Account_Number  9923934193
Interest_Rate            8
                        66
Name                Fatima
Account_Number  4694197536
Interest_Rate           10
                        72
Name                 Divya
Account_Number  2018026902
Interest_Rate            8
                        83
Name                  John
Account_Number  6286371115
Interest_Rate           10
                        89
Name                  Mani
Account_Number  8104201471
Interest_Rate            8
                        90
Name                 Priya
Account_Number  1854081204
Interest_Rate           10
                        95
Name                 Divya
Account_Number  2227960290
Interest_Rate            8
                        96
Name                 Priya
Account_Number  7623858346
Interest_Rate           10
                        98
Name                Fatima
Account_Number  6876844675
Interest_Rate            8
                        99
Name                Robert
Account_Number  7384888343
Interest_Rate           10
                       114
Name                 Priya
Account_Number  2419091580
Interest_Rate            8
                       122
Name                  Arun
Account_Number  5065806894
Interest_Rate            8
                       127
Name                 Aisha
Account_Number  8566865623
Interest_Rate           10
                       130
Name                  John
Account_Number  6581592079
Interest_Rate            8
                       134
Name                 Priya
Account_Number  4062509460
Interest_Rate            8
                       137
Name                 Divya
Account_Number  5358074925
Interest_Rate           10
                       142
Name                 Divya
Account_Number  3264447025
Interest_Rate            8
                       144
Name                 Priya
Account_Number  1953808599
Interest_Rate            8
                       146
Name                Fatima
Account_Number  1636419349
Interest_Rate           10
                       147
Name                  Mani
Account_Number  3538885340
Interest_Rate           10
                       151
Name                 Divya
Account_Number  1524116974
Interest_Rate           10
                       155
Name                  Kavi
Account_Number  7647684665
Interest_Rate            8
                       158
Name                 Priya
Account_Number  8470701471
Interest_Rate            8
                       162
Name                Robert
Account_Number  4968665189
Interest_Rate           10
                       167
Name                Fatima
Account_Number  4140980533
Interest_Rate           10
                       168
Name                 Kumar
Account_Number  4191510887
Interest_Rate            8
                       178
Name                  Arun
Account_Number  4436289238
Interest_Rate            8
                       181
Name                Robert
Account_Number  8408844684
Interest_Rate            8
                       186
Name                Fatima
Account_Number  2443139359
Interest_Rate           10
                       187
Name                 Priya
Account_Number  2006850274
Interest_Rate           10
                       190
Name                 Aisha
Account_Number  9828758479
Interest_Rate           10
                       193
Name                 Kumar
Account_Number  3439431034
Interest_Rate           10
                       194
Name                  John
Account_Number  4200521550
Interest_Rate            8
                       201
Name                  John
Account_Number  3428460279
Interest_Rate            8
                       202
Name                 Priya
Account_Number  2802285865
Interest_Rate           10
                       203
Name                  Kavi
Account_Number  5996492842
Interest_Rate           10
                       206
Name                Fatima
Account_Number  6805958302
Interest_Rate            8
                       207
Name                Robert
Account_Number  3114121674
Interest_Rate           10
                       211
Name                Robert
Account_Number  2472018118
Interest_Rate           10
                       212
Name                  John
Account_Number  7902593452
Interest_Rate            8
                       215
Name                Robert
Account_Number  5188366092
Interest_Rate            8
                       216
Name                 Kumar
Account_Number  6818514845
Interest_Rate           10
                       220
Name                  Arun
Account_Number  5664902036
Interest_Rate            8
                       222
Name                  Arun
Account_Number  1053004410
Interest_Rate           10
                       226
Name                Robert
Account_Number  4576040338
Interest_Rate           10
                       233
Name                  John
Account_Number  9619203515
Interest_Rate            8
                       236
Name                  Mani
Account_Number  7652516212
Interest_Rate           10
                       240
Name                  Mani
Account_Number  5758948157
Interest_Rate            8
                       244
Name                  Mani
Account_Number  4592400483
Interest_Rate            8
                       245
Name                 Aisha
Account_Number  5670547141
Interest_Rate            8
                       246
Name                 Aisha
Account_Number  7228915808
Interest_Rate            8
                       252
Name                  Kavi
Account_Number  5952717907
Interest_Rate            8
                       256
Name                Robert
Account_Number  7168629707
Interest_Rate            8
                       260
Name                 Priya
Account_Number  3350741615
Interest_Rate            8
                       266
Name                  Arun
Account_Number  6953043435
Interest_Rate           10
                       267
Name                Fatima
Account_Number  3795307410
Interest_Rate            8
                       268
Name                 Priya
Account_Number  1415299975
Interest_Rate           10
                       271
Name                  Kavi
Account_Number  3685282812
Interest_Rate            8
                       278
Name                Fatima
Account_Number  3976069715
Interest_Rate           10
                       280
Name                 Divya
Account_Number  1147647462
Interest_Rate            8
                       281
Name                 Kumar
Account_Number  7964369900
Interest_Rate            8
                       283
Name                  Kavi
Account_Number  5066819486
Interest_Rate            8
                       286
Name                 Aisha
Account_Number  7187927068
Interest_Rate            8
                       291
Name                  John
Account_Number  6341284846
Interest_Rate            8
                       298
Name                 Divya
Account_Number  8867197389
Interest_Rate           10
                       300
Name                 Priya
Account_Number  2421268097
Interest_Rate            8
                       303
Name                 Priya
Account_Number  3161315201
Interest_Rate           10
                       306
Name                 Kumar
Account_Number  2431511968
Interest_Rate           10
                       308
Name                  Mani
Account_Number  8820788478
Interest_Rate            8
                       309
Name                  Arun
Account_Number  4378949615
Interest_Rate           10
                       311
Name                 Divya
Account_Number  5237283698
Interest_Rate            8
                       314
Name                 Kumar
Account_Number  9655693081
Interest_Rate           10
                       323
Name                  John
Account_Number  7071936549
Interest_Rate            8
                       325
Name                  Arun
Account_Number  7888785835
Interest_Rate            8
                       327
Name                 Priya
Account_Number  3593270155
Interest_Rate           10
                       329
Name                Fatima
Account_Number  5791061194
Interest_Rate            8
                       331
Name                 Divya
Account_Number  6022630967
Interest_Rate           10
                       333
Name                 Divya
Account_Number  7895331576
Interest_Rate           10
                       340
Name                 Divya
Account_Number  3569195744
Interest_Rate            8
                       345
Name                 Divya
Account_Number  9555895960
Interest_Rate            8
                       358
Name                  Arun
Account_Number  3221004595
Interest_Rate           10
                       369
Name                 Kumar
Account_Number  6797361270
Interest_Rate            8
                       377
Name                Fatima
Account_Number  4652086724
Interest_Rate           10
                       384
Name                 Aisha
Account_Number  3264820791
Interest_Rate           10
                       387
Name                  Kavi
Account_Number  3912513960
Interest_Rate            8
                       391
Name                 Kumar
Account_Number  6508471071
Interest_Rate            8
                       394
Name                  Kavi
Account_Number  6931980688
Interest_Rate            8
                       397
Name                 Priya
Account_Number  5527100069
Interest_Rate            8
                       400
Name                  Mani
Account_Number  9165846120
Interest_Rate            8
                       403
Name                 Priya
Account_Number  6598473681
Interest_Rate            8
                       409
Name                 Aisha
Account_Number  1506542730
Interest_Rate           10
                       411
Name                Fatima
Account_Number  1845072515
Interest_Rate            8
                       415
Name                 Priya
Account_Number  3535860828
Interest_Rate            8
                       417
Name                 Priya
Account_Number  7484264658
Interest_Rate            8
                       420
Name                  Kavi
Account_Number  2986236926
Interest_Rate            8
                       426
Name                 Priya
Account_Number  5132557014
Interest_Rate            8
                       434
Name                 Kumar
Account_Number  8190718574
Interest_Rate            8
                       436
Name                  John
Account_Number  7495879342
Interest_Rate           10
                       438
Name                Fatima
Account_Number  6313967032
Interest_Rate           10
                       444
Name                 Kumar
Account_Number  4046481707
Interest_Rate           10
                       453
Name                  Mani
Account_Number  3610090766
Interest_Rate           10
                       475
Name                 Divya
Account_Number  8877508741
Interest_Rate           10
                       481
Name                  Kavi
Account_Number  1802012114
Interest_Rate           10
                       483
Name                 Kumar
Account_Number  6181642816
Interest_Rate            8
                       484
Name                Fatima
Account_Number  7210296385
Interest_Rate           10
                       488
Name                  John
Account_Number  4033245499
Interest_Rate            8
                       502
Name                  Kavi
Account_Number  7491569947
Interest_Rate            8
                       508
Name                  Mani
Account_Number  9063262163
Interest_Rate           10
                       510
Name                 Priya
Account_Number  7367313043
Interest_Rate            8
                       514
Name                Robert
Account_Number  2614735494
Interest_Rate           10
                       525
Name                 Divya
Account_Number  3781889303
Interest_Rate           10
                       534
Name                  Kavi
Account_Number  8832836179
Interest_Rate           10
                       536
Name                 Kumar
Account_Number  6597931280
Interest_Rate            8
                       538
Name                 Priya
Account_Number  1063861736
Interest_Rate           10
                       544
Name                Fatima
Account_Number  1416403056
Interest_Rate            8
                       547
Name                 Priya
Account_Number  4279216501
Interest_Rate            8
                       550
Name                  Kavi
Account_Number  8760573627
Interest_Rate            8
                       551
Name                  Arun
Account_Number  9830797057
Interest_Rate            8
                       552
Name                  John
Account_Number  6990566732
Interest_Rate           10
                       553
Name                 Divya
Account_Number  6380773283
Interest_Rate           10
                       557
Name                  Arun
Account_Number  9981139185
Interest_Rate           10
                       560
Name                 Aisha
Account_Number  7058122816
Interest_Rate            8
                       562
Name                  Kavi
Account_Number  7707370477
Interest_Rate           10
                       564
Name                 Aisha
Account_Number  1106555262
Interest_Rate            8
                       570
Name                  John
Account_Number  1602519549
Interest_Rate            8
                       572
Name                  John
Account_Number  6641067450
Interest_Rate           10
                       573
Name                 Aisha
Account_Number  8880417448
Interest_Rate            8
                       575
Name                 Divya
Account_Number  7675211095
Interest_Rate           10
                       577
Name                  Kavi
Account_Number  4560086011
Interest_Rate           10
                       580
Name                 Divya
Account_Number  7643400102
Interest_Rate           10
                       582
Name                Robert
Account_Number  6480700985
Interest_Rate           10
                       588
Name                  John
Account_Number  9096525843
Interest_Rate            8
                       591
Name                  Mani
Account_Number  1926033856
Interest_Rate           10
                       593
Name                  Mani
Account_Number  5864403417
Interest_Rate            8
                       597
Name                  Arun
Account_Number  9533729427
Interest_Rate           10
                       602
Name                  Arun
Account_Number  4638513572
Interest_Rate           10
                       606
Name                  John
Account_Number  8415009154
Interest_Rate           10
                       613
Name                 Kumar
Account_Number  7522130133
Interest_Rate           10
                       615
Name                 Priya
Account_Number  3649504286
Interest_Rate            8
                       616
Name                  Arun
Account_Number  4651628376
Interest_Rate           10
                       618
Name                  Kavi
Account_Number  5216486283
Interest_Rate            8
                       619
Name                 Kumar
Account_Number  4502770246
Interest_Rate            8
                       628
Name                Fatima
Account_Number  3012534926
Interest_Rate            8
                       631
Name                Robert
Account_Number  2826684598
Interest_Rate           10
                       637
Name                 Divya
Account_Number  1223500813
Interest_Rate            8
                       642
Name                Robert
Account_Number  3341784429
Interest_Rate           10
                       647
Name                 Aisha
Account_Number  6324950576
Interest_Rate            8
                       654
Name                  Kavi
Account_Number  2993445454
Interest_Rate            8
                       659
Name                Robert
Account_Number  6023656082
Interest_Rate           10
                       666
Name                 Priya
Account_Number  7885643572
Interest_Rate            8
                       673
Name                Fatima
Account_Number  8976171696
Interest_Rate           10
                       675
Name                 Aisha
Account_Number  4939787013
Interest_Rate            8
                       680
Name                 Priya
Account_Number  5849807973
Interest_Rate           10
                       683
Name                  Mani
Account_Number  8618950099
Interest_Rate            8
                       687
Name                  Mani
Account_Number  9892877082
Interest_Rate            8
                       690
Name                 Divya
Account_Number  8006334253
Interest_Rate           10
                       695
Name                 Divya
Account_Number  5264488016
Interest_Rate            8
                       698
Name                  Mani
Account_Number  6549857114
Interest_Rate            8
                       700
Name                 Aisha
Account_Number  9505418533
Interest_Rate            8
                       702
Name                  Kavi
Account_Number  3794112370
Interest_Rate            8
                       704
Name                Fatima
Account_Number  3150475640
Interest_Rate           10
                       708
Name                 Divya
Account_Number  3469715532
Interest_Rate           10
                       710
Name                  Arun
Account_Number  3238116117
Interest_Rate           10
                       711
Name                 Aisha
Account_Number  6023050824
Interest_Rate            8
                       713
Name                  Mani
Account_Number  9975242026
Interest_Rate           10
                       717
Name                  Mani
Account_Number  6098370298
Interest_Rate            8
                       718
Name                  John
Account_Number  7586914880
Interest_Rate           10
                       726
Name                Robert
Account_Number  5264982737
Interest_Rate            8
                       731
Name                 Divya
Account_Number  9525655435
Interest_Rate            8
                       732
Name                  Kavi
Account_Number  5680222833
Interest_Rate            8
                       736
Name                  John

10.	Fetch accounts with incomplete address info (City missing).

In [ ]:
df['City']=df['City'].fillna('Unknown')
for i in df.index:
   if df.loc[i,'City'] == 'Unknown':
      print(pd.DataFrame(df.loc[i,['Name','Account_Number']]))

                         3
Name                Robert
Account_Number  9970006983
                         5
Name                  John
Account_Number  5404141609
                        16
Name                  Arun
Account_Number  1744293433
                        25
Name                  John
Account_Number  4930987466
                        26
Name                 Divya
Account_Number  1572025740
                        35
Name                  Arun
Account_Number  6402651504
                        44
Name                 Aisha
Account_Number  3684251440
                        46
Name                Fatima
Account_Number  5662223622
                        49
Name                  Arun
Account_Number  7874167563
                        53
Name                 Kumar
Account_Number  9748881168
                        77
Name                 Priya
Account_Number  2927124440
                        80
Name                 Kumar
Account_Number  8813356661
                        81
Name                Robert
Account_Number  1721615534
                        87
Name                  Arun
Account_Number  9152971599
                        90
Name                 Priya
Account_Number  1854081204
                        98
Name                Fatima
Account_Number  6876844675
                       108
Name                Robert
Account_Number  5899318688
                       137
Name                 Divya
Account_Number  5358074925
                       139
Name                  John
Account_Number  3349189279
                       141
Name                  Mani
Account_Number  3135940691
                       146
Name                Fatima
Account_Number  1636419349
                       151
Name                 Divya
Account_Number  1524116974
                       152
Name                 Aisha
Account_Number  7940288800
                       155
Name                  Kavi
Account_Number  7647684665
                       167
Name                Fatima
Account_Number  4140980533
                       180
Name                  John
Account_Number  8769697365
                       185
Name                Robert
Account_Number  8849280605
                       189
Name                  John
Account_Number  5634009447
                       190
Name                 Aisha
Account_Number  9828758479
                       195
Name                 Priya
Account_Number  6079539213
                       202
Name                 Priya
Account_Number  2802285865
                       203
Name                  Kavi
Account_Number  5996492842
                       204
Name                  Kavi
Account_Number  6783425854
                       215
Name                Robert
Account_Number  5188366092
                       216
Name                 Kumar
Account_Number  6818514845
                       222
Name                  Arun
Account_Number  1053004410
                       226
Name                Robert
Account_Number  4576040338
                       227
Name                  John
Account_Number  3550268394
                       231
Name                Robert
Account_Number  3424898323
                       259
Name                 Priya
Account_Number  1427326345
                       268
Name                 Priya
Account_Number  1415299975
                       269
Name                  Mani
Account_Number  1480755340
                       277
Name                 Kumar
Account_Number  2302590308
                       280
Name                 Divya
Account_Number  1147647462
                       282
Name                Fatima
Account_Number  2751899686
                       285
Name                 Kumar
Account_Number  6765543160
                       286
Name                 Aisha
Account_Number  7187927068
                       299
Name                  John
Account_Number  5832826146
                       309
Name                  Arun
Account_Number  4378949615
                       331
Name                 Divya
Account_Number  6022630967
                       333
Name                 Divya
Account_Number  7895331576
                       336
Name                Fatima
Account_Number  3609071311
                       341
Name                 Priya
Account_Number  7125148928
                       352
Name                  Arun
Account_Number  4456730631
                       357
Name                 Divya
Account_Number  1185415006
                       361
Name                  Mani
Account_Number  9426245804
                       367
Name                  Kavi
Account_Number  5149907889
                       391
Name                 Kumar
Account_Number  6508471071
                       399
Name                 Divya
Account_Number  2873655622
                       404
Name                Fatima
Account_Number  7058072092
                       424
Name                 Divya
Account_Number  5500944179
                       449
Name                Fatima
Account_Number  1322524758
                       463
Name                 Priya
Account_Number  2751852446
                       476
Name                  John
Account_Number  6952019461
                       488
Name                  John
Account_Number  4033245499
                       494
Name                  Mani
Account_Number  1906916890
                       496
Name                  Kavi
Account_Number  7599746731
                       502
Name                  Kavi
Account_Number  7491569947
                       517
Name                  Arun
Account_Number  2428819601
                       525
Name                 Divya
Account_Number  3781889303
                       528
Name                  Mani
Account_Number  5381881256
                       545
Name                  Arun
Account_Number  4102034036
                       546
Name                Fatima
Account_Number  5482940168
                       570
Name                  John
Account_Number  1602519549
                       576
Name                 Kumar
Account_Number  9295344222
                       623
Name                  Kavi
Account_Number  1222408203
                       650
Name                 Kumar
Account_Number  3467174199
                       653
Name                Fatima
Account_Number  1487918440
                       654
Name                  Kavi
Account_Number  2993445454
                       666
Name                 Priya
Account_Number  7885643572
                       683
Name                  Mani
Account_Number  8618950099
                       686
Name                 Priya
Account_Number  6431823210
                       697
Name                 Divya
Account_Number  3810883829
                       701
Name                 Aisha
Account_Number  5637548584
                       704
Name                Fatima
Account_Number  3150475640
                       727
Name                 Aisha
Account_Number  3412903393
                       736
Name                  John
Account_Number  1349097198
                       739
Name                Fatima
Account_Number  9458208500
                       746
Name                  Mani
Account_Number  1097439251
                       755
Name                  Arun
Account_Number  5431571011
                       764
Name                  Kavi
Account_Number  4405962309
                       778
Name                  Kavi
Account_Number  3747251950
                       787
Name                 Divya
Account_Number  6520165386
                       788
Name                 Divya
Account_Number  7152469250
                       793
Name                  Kavi
Account_Number  3786782355
                       802
Name                  John
Account_Number  2902842347
                       803
Name                Robert
Account_Number  3435948959
                       809
Name                  Kavi
Account_Number  5243462212
                       812
Name                 Aisha
Account_Number  9275613220
                       814
Name                  Kavi
Account_Number  2178025229
                       827
Name                 Divya
Account_Number  9883938698
                       830
Name                 Divya
Account_Number  3242957749
                       835
Name                  Kavi
Account_Number  1980585793
                       841
Name                 Kumar
Account_Number  4766347066
                       846
Name                  John
Account_Number  4573040472
                       849
Name                  Mani
Account_Number  5113103247
                       869
Name                 Aisha
Account_Number  8632813611
                       874
Name                 Kumar
Account_Number  9918794408
                       879
Name                  John
Account_Number  2033149439
                       892
Name                Fatima
Account_Number  1710901851
                       899
Name                  John
Account_Number  3047065729
                       915
Name                Fatima
Account_Number  1717062002
                       916
Name                Robert
Account_Number  1449705219
                       921
Name                 Aisha
Account_Number  6285594975
                       946
Name                  Arun
Account_Number  3325608075
                       953
Name                Robert
Account_Number  1094558508
                       975
Name                  Mani
Account_Number  6764453077
                       977
Name                 Aisha
Account_Number  4469625477
                       994
Name                  John
Account_Number  3781436559
                       995
Name                  Arun
Account_Number  6358616360
                      1003
Name                  John
Account_Number  4278320858
                      1011
Name                  Kavi
Account_Number  9893411802
                      1020
Name                  Arun
Account_Number  6716508817
                      1035
Name                 Aisha
Account_Number  7445314129
                      1044
Name                  Mani
Account_Number  3156350962
                      1070
Name                  Mani
Account_Number  3748106915
                      1073
Name                  Arun
Account_Number  5356674636
                      1080
Name                 Divya
Account_Number  4307492693
                      1084
Name                Robert
Account_Number  4258538229
                      1111
Name                 Kumar
Account_Number  9864076713
                      1116
Name                 Aisha
Account_Number  1065380010
                      1119
Name                  Kavi
Account_Number  8021227515
                      1134
Name                  Arun
Account_Number  1120874488
                      1153
Name                Robert
Account_Number  3261986721
                      1160
Name                  Mani
Account_Number  2461519236
                      1170
Name                  Kavi
Account_Number  7511699372
                      1180
Name                  Kavi
Account_Number  7820848040
                      1188
Name                 Aisha
Account_Number  4268152370
                      1190
Name                 Divya
Account_Number  1844118851
                      1191
Name                 Aisha
Account_Number  3280025373
                      1193
Name                Robert
Account_Number  1707707042
                      1195
Name                  John
Account_Number  2606590574
                      1210
Name                 Kumar
Account_Number  9446300979
                      1214
Name                  Kavi
Account_Number  6108281393
                      1223
Name                  Mani
Account_Number  5060679193
                      1232
Name                  Mani
Account_Number  5109720284
                      1233
Name                Robert
Account_Number  1282040034
                      1268
Name                Fatima
Account_Number  4819655983
                      1271
Name                 Kumar
Account_Number  3877278971
                      1273
Name                  Arun
Account_Number  6393829747
                      1287
Name                 Aisha
Account_Number  7217319457
                      1302
Name                 Divya
Account_Number  9220512611
                      1307
Name                Robert
Account_Number  6408000320
                      1318
Name                 Kumar
Account_Number  4658988698
                      1325
Name                 Divya
Account_Number  2925719655
                      1331
Name                  Kavi
Account_Number  6540156635
                      1345
Name                  Kavi
Account_Number  9723103717
                      1348
Name                Robert
Account_Number  7432682963
                      1356
Name                  John
Account_Number  1272753908
                      1371
Name                 Aisha
Account_Number  6508947605
                      1376
Name                 Kumar
Account_Number  8199983710
                      1382
Name                 Divya
Account_Number  6651488744
                      1395
Name                  Arun
Account_Number  1304545192
                      1398
Name                 Kumar
Account_Number  5782803379
                      1407
Name                  John
Account_Number  3467654750
                      1416
Name                 Aisha
Account_Number  6921817902
                      1424
Name                  Arun
Account_Number  8947649034
                      1426
Name                  Kavi
Account_Number  8077621844
                      1444
Name                Fatima
Account_Number  5446919848
                      1455
Name                 Kumar
Account_Number  3379967701
                      1460
Name                Fatima
Account_Number  8562948850
                      1474
Name                Fatima
Account_Number  9093869994
                      1477
Name                 Kumar
Account_Number  2229235710
                      1491
Name                  John
Account_Number  9377221423
                      1507
Name                 Kumar
Account_Number  5143257160
                      1520
Name                  Kavi
Account_Number  7487871698
                      1549
Name                 Aisha
Account_Number  9556812617
                      1553
Name                  Arun
Account_Number  3602675095
                      1560
Name                  Arun
Account_Number  5731146512
                      1567
Name                 Priya
Account_Number  5621306591
                      1568
Name                  Kavi
Account_Number  5525406518
                      1579
Name                 Aisha
Account_Number  5942828781
                      1580
Name                 Aisha
Account_Number  3276685436
                      1583
Name                 Aisha
Account_Number  5854010112
                      1589
Name                Robert
Account_Number  8938741538
                      1611
Name                 Kumar
Account_Number  3597752357
                      1613
Name                  Mani
Account_Number  4950269982
                      1615
Name                 Kumar
Account_Number  5327476349
                      1622
Name                Robert
Account_Number  7052454899
                      1636
Name                Fatima
Account_Number  7672831964
                      1640
Name                Fatima
Account_Number  9196639690
                      1645
Name                  John
Account_Number  7339395264
                      1655
Name                 Kumar
Account_Number  2106131810
                      1663
Name                 Priya
Account_Number  7845272311
                      1675
Name                 Priya
Account_Number  9910343383
                      1679
Name                 Aisha
Account_Number  3267204536
                      1688
Name                 Priya
Account_Number  2701519677
                      1698
Name                 Priya
Account_Number  3814247241
                      1705
Name                  John
Account_Number  2450453039
                      1714
Name                  Arun
Account_Number  6039532259
                      1716
Name                  Kavi
Account_Number  2139084506
                      1722
Name                 Kumar
Account_Number  9182436046
                      1725
Name                  Mani
Account_Number  7546225123
                      1744
Name                  Mani
Account_Number  3864330136
                      1767
Name                 Kumar
Account_Number  9543707135
                      1774
Name                Robert
Account_Number  8436603416
                      1834
Name                 Divya
Account_Number  9905487072
                      1840
Name                 Priya
Account_Number  3239286733
                      1844
Name                 Kumar
Account_Number  4294905109
                      1845
Name                  John
Account_Number  4132894715
                      1847
Name                 Divya
Account_Number  7689118277
                      1855
Name                Fatima
Account_Number  6349223946
                      1859
Name                  Kavi
Account_Number  8078972493
                      1885
Name                  John
Account_Number  8044484433
                      1891
Name                  John
Account_Number  4288002114
                      1898
Name                Fatima
Account_Number  7509889835
                      1903
Name                 Aisha
Account_Number  1719198554
                      1933
Name                Fatima
Account_Number  8192685657
                      1936
Name                 Priya
Account_Number  6247123469
                      1938
Name                 Aisha
Account_Number  3413722606
                      1940
Name                Fatima
Account_Number  3262583332
                      1947
Name                Fatima
Account_Number  3172375672
                      1953
Name                 Priya
Account_Number  1340372668
                      1963
Name                 Kumar
Account_Number  5503833103
                      1967
Name                  John
Account_Number  5487726729
                      1972
Name                 Priya
Account_Number  6743876614
                      1999
Name                 Priya
Account_Number  2166095843
                      2004
Name                  Arun
Account_Number  3565622031
                      2027
Name                Fatima
Account_Number  3173525098
                      2039
Name                 Priya
Account_Number  2398978381
                      2041
Name                 Priya
Account_Number  9363102182
                      2051
Name                 Divya
Account_Number  8230073596
                      2054
Name                 Aisha
Account_Number  3180234468
                      2077
Name                Robert
Account_Number  2434920468
                      2088
Name                 Kumar
Account_Number  6401682054
                      2102
Name                 Aisha
Account_Number  4396074531
                      2109
Name                  Mani
Account_Number  8607475437
                      2123
Name                  John
Account_Number  4832653885
                      2128
Name                  Kavi
Account_Number  3045790964
                      2129
Name                  John
Account_Number  8846070496
                      2158
Name                 Kumar
Account_Number  8644864949
                      2164
Name                 Aisha
Account_Number  6616304549
                      2167
Name                 Aisha
Account_Number  9147066111
                      2171
Name                Fatima
Account_Number  9280088445
                      2175
Name                Robert
Account_Number  6296836897
                      2176
Name                 Kumar
Account_Number  5350685869
                      2190
Name                 Divya

**E. Calculated Columns / Transformations (10 Questions)**

1.	Add Total_Balance = Balance + Fixed_Deposit + Recurring_Deposit.

In [ ]:
df['Total_Balance']=df['Balance'] + df['Fixed_Deposit'] + df['Recurring_Deposit']

2.	Add Loan_Status flag (1 if Loan_Amount > 0 else 0).

In [ ]:
df['Loan_Status']=df['Loan_Amount']
for i in df.index:
  if df.loc[i,'Loan_Status'] > 0:
    df.loc[i,'Loan_Staus'] = '1'
  else:
        df.loc[i,'Loan_Staus'] = '0'

3.	Add Customer_Tenure = Current_Date − Account_Open_Date.

In [ ]:
from datetime import date
df['Account_Open_Date'] = pd.to_datetime(df['Account_Open_Date'], format='%d-%m-%y', errors='coerce')
df['Customer_Tenure'] = (pd.Timestamp.now() - df['Account_Open_Date']).dt.days

4.	Create Account_Category (Low Balance, Medium, High Balance).

In [ ]:
df['Account_Category'] = df['Balance']
x=df['Balance'].median()
for i in df.index:
  if df.loc[i,'Account_Category'] < 2000000:
    df.loc[i,'Account_Category'] = 'Low Balance'
  elif df.loc[i,'Account_Category'] <= x:
    df.loc[i,'Account_Category'] = 'Median Balance'
  elif df.loc[i,'Account_Category'] > x:
    df.loc[i,'Account_Category'] = 'High Balance'

/tmp/ipykernel_12795/1124041886.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Low Balance' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[i,'Account_Category'] = 'Low Balance'

5.	Convert Name, Branch, Account_Type to proper title case.

In [ ]:
df.columns=df.columns.str.strip()

6.	Extract Year & Month from Transaction_Date.

In [ ]:
df['Transaction_Date'] = pd.to_datetime(df['Transaction_Date'], format='%d-%m-%y', errors='coerce')
df['year'] = df['Transaction_Date'].dt.year
df['month'] = df['Transaction_Date'].dt.month

7.	Convert all email to lowercase for consistency.

In [ ]:
df['Email']=df['Email'].str.lower()

8.	Add Interest_Per_Year = Loan_Amount × (Interest_Rate/100).

In [ ]:
df['Interest_per_year'] = df['Loan_Amount'] * (df['Interest_Rate'] /100)

9.	Add Zero_Balance_Flag (1 if Balance = 0 else 0).

In [ ]:
df['Zero_Balance_Flag']=df['Balance']
for i in df.index:
  if df.loc[i,'Zero_Balance_Flag'] == 0:
    df.loc[i,'Zero_Balance_Flag'] = '1'
  else:
    df.loc[i,'Zero_Balance_Flag'] = '0'

/tmp/ipykernel_12795/519713105.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[i,'Zero_Balance_Flag'] = '0'
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

10.	Remove extra spaces in Name, City, Country columns.

In [ ]:
df['Name']=df['Name'].str.strip()
df['City']=df['City'].str.strip()
df['Country']=df['Country'].str.strip()

***F. Sorting / Ranking / Aggregation (10 Questions)***

1.	Find top 10 customers with the highest Balance.

In [ ]:
df.sort_values("Balance",ascending=False,).head(10)

,Account_ID,Account_Number,Name,Account_Type,Balance,Fixed_Deposit,Recurring_Deposit,Loan_Amount,Interest_Rate,Branch,...,Notes,Total_Balance,Loan_Status,Loan_Staus,Customer_Tenure,Account_Category,year,month,Interest_per_year,Zero_Balance_Flag
2081,ACC102081,6863569894,Priya,Unknown,4999895.0,51238,44230,601202.0,10,Hyderabad,...,Check,5095363.0,601202.0,1,2545,High Balance,2023.0,3.0,60120.20,0
118,ACC100118,4991857278,Divya,Current,4999384.0,61035,8210,1584918.0,14,Mumbai,...,Remove,5068629.0,1584918.0,1,2238,High Balance,NaN,NaN,221888.52,0
1009,ACC101009,7870211053,Arun,Current,4998278.0,34070,7749,0.0,12,Mumbai,...,NaN,5040097.0,0.0,0,465,High Balance,2021.0,10.0,0.00,0
2864,ACC102864,5483668791,Priya,Savings,4995999.0,81806,20224,59260.0,14,Delhi,...,Check,5098029.0,59260.0,1,3465,High Balance,NaN,NaN,8296.40,0
690,ACC100690,8006334253,Divya,Current,4994661.0,74300,178,1391699.0,10,Chennai,...,Remove,5069139.0,1391699.0,1,1900,High Balance,2018.0,12.0,139169.90,0
1178,ACC101178,2230357004,Kavi,RD,4991257.0,50787,42683,1849819.0,14,Chennai,...,Temp,5084727.0,1849819.0,1,1691,High Balance,2017.0,9.0,258974.66,0
3570,ACC103570,2812474758,Divya,FD,4990602.0,88324,30732,0.0,8,Bangalore,...,NaN,5109658.0,0.0,0,3735,High Balance,2018.0,12.0,0.00,0
1577,ACC101577,1934340669,Aisha,FD,4990064.0,30779,35292,1622466.0,14,Hyderabad,...,Remove,5056135.0,1622466.0,1,2251,High Balance,2019.0,8.0,227145.24,0
1571,ACC101571,5709273401,John,Unknown,4987341.0,25759,21464,597192.0,12,Hyderabad,...,Check,5034564.0,597192.0,1,3192,High Balance,2017.0,6.0,71663.04,0
2581,ACC102581,8205609314,Priya,Current,4985280.0,99948,2294,297442.0,16,Hyderabad,...,NaN,5087522.0,297442.0,1,547,High Balance,2023.0,6.0,47590.72,0

2.	Find top 10 customers with the highest Loan_Amount.

In [ ]:
df.sort_values('Loan_Amount',ascending=False).head(10)

,Account_ID,Account_Number,Name,Account_Type,Balance,Fixed_Deposit,Recurring_Deposit,Loan_Amount,Interest_Rate,Branch,...,Notes,Total_Balance,Loan_Status,Loan_Staus,Customer_Tenure,Account_Category,year,month,Interest_per_year,Zero_Balance_Flag
4979,ACC104979,6861070705,Robert,Savings,3068212.0,771,18559,1997393.0,10,unknown,...,Check,3087542.0,1997393.0,1,3149,High Balance,2016.0,12.0,199739.30,0
578,ACC100578,1479479185,Aisha,Current,4686137.0,23424,20976,1996248.0,12,Bangalore,...,Temp,4730537.0,1996248.0,1,1186,High Balance,NaN,NaN,239549.76,0
768,ACC100768,3083532187,Aisha,RD,1175328.0,13936,10019,1994803.0,8,Delhi,...,NaN,1199283.0,1994803.0,1,2060,Low Balance,2017.0,4.0,159584.24,0
1683,ACC101683,1011852578,Divya,RD,4369082.0,39276,31711,1994645.0,16,Mumbai,...,NaN,4440069.0,1994645.0,1,2509,High Balance,2021.0,10.0,319143.20,0
26,ACC100026,1572025740,Divya,Savings,3987776.0,5713,49407,1994168.0,12,Delhi,...,Remove,4042896.0,1994168.0,1,2311,High Balance,2021.0,2.0,239300.16,0
2020,ACC102020,2167723413,Priya,Savings,1532944.0,45828,37931,1992893.0,14,Hyderabad,...,NaN,1616703.0,1992893.0,1,1974,Low Balance,2017.0,2.0,279005.02,0
833,ACC100833,2607765440,John,Current,4548959.0,83994,45765,1991982.0,10,Hyderabad,...,Temp,4678718.0,1991982.0,1,2715,High Balance,2024.0,11.0,199198.20,0
4603,AC-104603,8143481509,Aisha,Savings,4248296.0,63013,11013,1991961.0,12,Hyderabad,...,NaN,4322322.0,1991961.0,1,1084,High Balance,2024.0,4.0,239035.32,0
4733,ACC104733,9848020067,Kumar,Savings,880425.0,91151,48773,1991624.0,10,unknown,...,Remove,1020349.0,1991624.0,1,1237,Low Balance,2015.0,10.0,199162.40,0
2464,ACC102464,1854353168,Fatima,Savings,954817.0,42453,36544,1990464.0,10,Bangalore,...,Remove,1033814.0,1990464.0,1,1410,Low Balance,2020.0,3.0,199046.40,0

3.	Find average balance per branch.

In [ ]:
df.groupby('Country')['Balance'].mean()

Country
India            2.516225e+06
UAE              2.443085e+06
Unites States    2.603638e+06
unknown          2.391839e+06
Name: Balance, dtype: float64

4.	Find total loan amount per country.

In [ ]:
df.groupby('Country')['Loan_Amount'].sum()

Country
India            768976469.0
UAE              802898710.0
Unites States    785230663.0
unknown          443817830.0
Name: Loan_Amount, dtype: float64

5.	Sort customers by Account_Open_Date.

In [ ]:
df.sort_values(by='Account_Open_Date')

,Account_ID,Account_Number,Name,Account_Type,Balance,Fixed_Deposit,Recurring_Deposit,Loan_Amount,Interest_Rate,Branch,...,Notes,Total_Balance,Loan_Status,Loan_Staus,Customer_Tenure,Account_Category,year,month,Interest_per_year,Zero_Balance_Flag
2871,ACC102871,5786120324,Robert,Unknown,101803.0,23883,11438,150749.0,12,Mumbai,...,Temp,137124.0,150749.0,1,4112,Low Balance,2017.0,1.0,18089.88,0
4014,ACC104014,9775680931,Priya,RD,3267300.0,45129,18152,1888979.0,16,Hyderabad,...,Remove,3330581.0,1888979.0,1,4110,High Balance,2024.0,11.0,302236.64,0
2255,ACC102255,6514279042,Mani,Current,3425057.0,34187,38463,1466968.0,14,Mumbai,...,Temp,3497707.0,1466968.0,1,4109,High Balance,2020.0,10.0,205375.52,0
1382,ACC101382,6651488744,Divya,Savings,2184943.0,92692,37365,1108557.0,16,Mumbai,...,NaN,2315000.0,1108557.0,1,4109,Median Balance,2020.0,11.0,177369.12,0
323,ACC100323,7071936549,John,Current,1608332.0,91737,44958,247137.0,8,Hyderabad,...,Remove,1745027.0,247137.0,1,4107,Low Balance,2021.0,3.0,19770.96,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4770,ACC104770,9860663940,John,Savings,1494365.0,16174,13351,0.0,10,Delhi,...,NaN,1523890.0,0.0,0,469,Low Balance,2015.0,2.0,0.00,0
1283,ACC101283,3554623201,Mani,RD,4042353.0,9390,33777,860735.0,8,Mumbai,...,Remove,4085520.0,860735.0,1,469,High Balance,2015.0,10.0,68858.80,0
394,ACC100394,6931980688,Kavi,FD,4012118.0,565,40180,772780.0,8,Hyderabad,...,NaN,4052863.0,772780.0,1,468,High Balance,2023.0,8.0,61822.40,0
3608,ACC103608,9790924229,John,Unknown,3908296.0,13163,32711,1208163.0,8,Delhi,...,Remove,3954170.0,1208163.0,1,467,High Balance,2016.0,8.0,96653.04,0
1009,ACC101009,7870211053,Arun,Current,4998278.0,34070,7749,0.0,12,Mumbai,...,NaN,5040097.0,0.0,0,465,High Balance,2021.0,10.0,0.00,0

6.	Sort customers by Loan_Interest_Rate descending.

In [ ]:
df.sort_values('Interest_Rate',ascending=False)

,Account_ID,Account_Number,Name,Account_Type,Balance,Fixed_Deposit,Recurring_Deposit,Loan_Amount,Interest_Rate,Branch,...,Notes,Total_Balance,Loan_Status,Loan_Staus,Customer_Tenure,Account_Category,year,month,Interest_per_year,Zero_Balance_Flag
6,ACC100006,5819331062,Kavi,Savings,4344539.0,23776,30080,15939.0,16,Delhi,...,NaN,4398395.0,15939.0,1,2115,High Balance,2016.0,10.0,2550.24,0
4997,ACC104997,5875650079,Arun,Savings,4579182.0,85525,49965,325034.0,16,Bangalore,...,Temp,4714672.0,325034.0,1,1574,High Balance,2018.0,5.0,52005.44,0
4995,ACC104995,1905811747,Divya,RD,4254142.0,26651,4944,556284.0,16,Chennai,...,Temp,4285737.0,556284.0,1,893,High Balance,2023.0,6.0,89005.44,0
4991,ACC104991,4468637158,Aisha,Current,3775023.0,46673,19072,1393603.0,16,Hyderabad,...,NaN,3840768.0,1393603.0,1,3041,High Balance,2020.0,4.0,222976.48,0
12,ACC100012,1187276799,Kavi,Savings,1368175.0,43484,17453,1699536.0,16,Delhi,...,Check,1429112.0,1699536.0,1,3986,Low Balance,2024.0,4.0,271925.76,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3924,ACC103924,6102564076,Divya,Savings,1996426.0,37062,45972,1281791.0,8,Bangalore,...,Temp,2079460.0,1281791.0,1,1226,Low Balance,2016.0,10.0,102543.28,0
4992,ACC104992,7462281200,Divya,FD,2417439.0,50883,3588,1171066.0,8,Chennai,...,Check,2471910.0,1171066.0,1,1941,Median Balance,2017.0,2.0,93685.28,0
4972,ACC104972,5391656155,Kavi,FD,822444.0,77194,45689,1651854.0,8,Delhi,...,Temp,945327.0,1651854.0,1,932,Low Balance,2021.0,4.0,132148.32,0
4956,ACC104956,2287201905,Robert,Current,4163709.0,62245,15336,923038.0,8,Bangalore,...,Remove,4241290.0,923038.0,1,758,High Balance,2019.0,3.0,73843.04,0
4953,ACC104953,2166042042,Kumar,Current,139070.0,71474,48656,1217889.0,8,Chennai,...,Check,259200.0,1217889.0,1,2328,Low Balance,2018.0,2.0,97431.12,0

7.	Identify branch with maximum customers.

In [ ]:
df['Branch'].value_counts(ascending=True)

Branch
unknown      290
Delhi        532
Hyderabad    546
Bangalore    564
Chennai      572
Mumbai       576
Name: count, dtype: int64

8.	Find total deposits per year.

In [ ]:
df.groupby('year')['Deposit'].sum()

year
2015.0    19834107
2016.0    25722109
2017.0    22252110
2018.0    21846878
2019.0    23636953
2020.0    23128951
2021.0    21418117
2022.0    20962412
2023.0    23392456
2024.0    20103522
Name: Deposit, dtype: int64

9.	Find customer with the highest number of withdrawals.

In [ ]:
for i in df.index:
  if df.loc[i,'Withdrawal'] == df['Withdrawal'].max():
    print(df.loc[i])

Account_ID                     ACC101529
Account_Number                6206480755
Name                                Kavi
Account_Type                     Current
Balance                        2444839.0
Fixed_Deposit                      35878
Recurring_Deposit                  24923
Loan_Amount                    1065698.0
Interest_Rate                         14
Branch                           Chennai
City                             Chennai
Country                              UAE
Email                     kavi@gmail.com
Phone_Number                9834219730.0
Transaction_Type                     DBT
Withdrawal                        199997
Deposit                            18659
Transaction_Date     2024-04-20 00:00:00
Account_Open_Date    2020-07-26 00:00:00
Notes                              Check
Total_Balance                  2505640.0
Loan_Status                    1065698.0
Loan_Staus                             1
Customer_Tenure                     2080
Account_Category            High Balance
year                              2024.0
month                                4.0
Interest_per_year              149197.72
Zero_Balance_Flag                      0
Name: 1529, dtype: object

10.	Compute average transaction value per branch.

In [ ]:

df.groupby('Branch')['Withdrawal'].mean()

Branch
Bangalore    77574.948582
Chennai      74471.101399
Delhi        71996.998120
Hyderabad    78074.879121
Mumbai       69349.482639
unknown      75277.731034
Name: Withdrawal, dtype: float64

***G. Advanced Cleaning & Validation (10 Questions)***

1.	Detect inconsistent date formats in Transaction_Date.

In [ ]:
v=df['Transaction_Date'].isna()
for i in v.index:
  if v[i] == True:
    df.drop(i,inplace=True)

2.	Validate Email format using regex.

3.	Identify customers appearing with multiple phone numbers.

In [ ]:
v=df['Phone_Number'].duplicated()
for i in v.index:
  if v[i] == True:
    print([i])

[37]
[48]
[105]
[119]
[148]
[161]
[172]
[187]
[188]
[194]
[197]
[217]
[240]
[253]
[254]
[311]
[344]
[349]
[410]
[438]
[444]
[445]
[449]
[481]
[514]
[562]
[576]
[580]
[595]
[680]
[683]
[737]
[776]
[787]
[796]
[804]
[808]
[850]
[864]
[887]
[889]
[926]
[960]
[999]
[1007]
[1020]
[1023]
[1072]
[1081]
[1088]
[1119]
[1156]
[1160]
[1162]
[1168]
[1181]
[1224]
[1240]
[1267]
[1277]
[1295]
[1307]
[1309]
[1314]
[1329]
[1380]
[1428]
[1438]
[1464]
[1485]
[1514]
[1542]
[1549]
[1579]
[1587]
[1595]
[1598]
[1626]
[1629]
[1646]
[1659]
[1685]
[1706]
[1707]
[1727]
[1751]
[1767]
[1784]
[1787]
[1795]
[1810]
[1828]
[1847]
[1848]
[1859]
[1862]
[1876]
[1895]
[1898]
[1900]
[1903]
[1914]
[1933]
[1958]
[1967]
[1978]
[2001]
[2011]
[2013]
[2021]
[2025]
[2039]
[2079]
[2101]
[2114]
[2129]
[2131]
[2133]
[2171]
[2193]
[2194]
[2198]
[2251]
[2254]
[2293]
[2318]
[2322]
[2339]
[2352]
[2358]
[2381]
[2403]
[2405]
[2422]
[2429]
[2442]
[2454]
[2455]
[2466]
[2494]
[2510]
[2513]
[2521]
[2523]
[2539]
[2551]
[2558]
[2616]
[2617]
[2618]
[2619]
[2640]
[2644]
[2657]
[2669]
[2675]
[2717]
[2723]
[2788]
[2793]
[2798]
[2810]
[2817]
[2821]
[2828]
[2908]
[2959]
[2999]
[3040]
[3060]
[3080]
[3090]
[3105]
[3113]
[3116]
[3127]
[3133]
[3139]
[3150]
[3151]
[3157]
[3161]
[3196]
[3208]
[3221]
[3249]
[3277]
[3280]
[3294]
[3297]
[3300]
[3304]
[3313]
[3334]
[3343]
[3379]
[3399]
[3438]
[3446]
[3460]
[3464]
[3482]
[3504]
[3512]
[3518]
[3556]
[3570]
[3604]
[3644]
[3647]
[3650]
[3670]
[3671]
[3675]
[3700]
[3765]
[3770]
[3786]
[3805]
[3816]
[3828]
[3837]
[3840]
[3861]
[3878]
[3888]
[3903]
[3925]
[3930]
[3943]
[3954]
[3964]
[3988]
[4059]
[4067]
[4085]
[4130]
[4132]
[4133]
[4147]
[4149]
[4150]
[4178]
[4208]
[4216]
[4225]
[4231]
[4239]
[4248]
[4249]
[4257]
[4376]
[4380]
[4386]
[4400]
[4410]
[4414]
[4424]
[4429]
[4445]
[4469]
[4476]
[4505]
[4529]
[4534]
[4541]
[4554]
[4566]
[4586]
[4592]
[4600]
[4611]
[4648]
[4650]
[4673]
[4692]
[4701]
[4725]
[4799]
[4819]
[4855]
[4883]
[4891]
[4914]
[4928]
[4934]
[4956]
[4971]
[4980]

4.	Detect outliers in Balance using IQR method.

5.	Validate Account_Type values (must be Savings, Current, FD, RD).

In [ ]:
df['Account_Type'].value_counts()

Account_Type
Current    909
Savings    869
FD         599
RD         304
Unknown    266
Name: count, dtype: int64

6.	Identify mismatched Branch vs City combinations.

In [ ]:
for i in df.index:
  if df.loc[i,'Branch'] != df.loc[i,'City']:
    df.loc[i]

7.	Clean and standardize all text columns (strip, lower, title).

In [ ]:
#strip:
df.columns=df.columns.str.strip()
#lower:
df.columns=df.columns.str.lower()
#title:
df.columns=df.columns.str.title()

8.	Identify invalid Account_ID formats.

In [ ]:
for i in df.index:
  if '@' not in df.loc[i,'Email']:
    df.loc[i]
  elif '.com' not in df.loc[i,'Email']:
    df.loc[i]
  elif '@@' in df.loc[i,'Email']:
    df.loc[i]

9.	Remove irrelevant columns (Notes, Misc, Temp fields).

In [ ]:
df.drop('Notes',axis=1,inplace=True)

In [ ]:
df.columns

Index(['Account_Id', 'Account_Number', 'Name', 'Account_Type', 'Balance',
       'Fixed_Deposit', 'Recurring_Deposit', 'Loan_Amount', 'Interest_Rate',
       'Branch', 'City', 'Country', 'Email', 'Phone_Number',
       'Transaction_Type', 'Withdrawal', 'Deposit', 'Transaction_Date',
       'Account_Open_Date', 'Total_Balance', 'Loan_Status', 'Loan_Staus',
       'Customer_Tenure', 'Account_Category', 'Year', 'Month',
       'Interest_Per_Year', 'Zero_Balance_Flag'],
      dtype='object')

10.	Convert all Transaction_Date entries to datetime and sort.

In [ ]:
df.sort_values(by='Transaction_Date')

,Account_Id,Account_Number,Name,Account_Type,Balance,Fixed_Deposit,Recurring_Deposit,Loan_Amount,Interest_Rate,Branch,...,Account_Open_Date,Total_Balance,Loan_Status,Loan_Staus,Customer_Tenure,Account_Category,Year,Month,Interest_Per_Year,Zero_Balance_Flag
1348,ACC101348,7432682963,Robert,RD,1473331.0,75553,47591,484065.0,8,Bangalore,...,2021-07-01,1596475.0,484065.0,1,1740,Low Balance,2015.0,1.0,38725.20,0
4202,ACC104202,8440267812,John,FD,3054860.0,87108,18528,1672330.0,10,unknown,...,2022-02-08,3160496.0,1672330.0,1,1518,High Balance,2016.0,1.0,167233.00,0
2561,ACC102561,3913061043,Robert,Savings,2847201.0,62190,42299,850874.0,12,Hyderabad,...,2016-01-16,2951690.0,850874.0,1,3733,High Balance,2016.0,1.0,102104.88,0
1341,ACC101341,3805710060,Robert,Current,1342696.0,94534,37985,458836.0,12,Bangalore,...,2016-03-14,1475215.0,458836.0,1,3675,Low Balance,2017.0,1.0,55060.32,0
1522,ACC101522,1006897498,Divya,Savings,908225.0,3961,35382,670226.0,16,Bangalore,...,2020-02-25,947568.0,670226.0,1,2232,Low Balance,2018.0,1.0,107236.16,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1508,ACC101508,6107255052,Robert,Current,1217843.0,4170,27666,785450.0,16,Delhi,...,2016-02-21,1249679.0,785450.0,1,3697,Low Balance,2015.0,12.0,125672.00,0
3236,ACC103236,8014959963,Arun,RD,2417439.0,89882,16876,1936498.0,14,Hyderabad,...,2020-01-28,2524197.0,1936498.0,1,2260,Median Balance,2016.0,12.0,271109.72,0
352,ACC100352,4456730631,Arun,Savings,2417439.0,14963,11580,1741864.0,14,Bangalore,...,2024-12-19,2443982.0,1741864.0,1,473,Median Balance,2016.0,12.0,243860.96,0
4241,ACC104241,7899733926,Aisha,Current,922228.0,3501,33685,1112287.0,10,Chennai,...,2021-01-26,959414.0,1112287.0,1,1896,Low Balance,2021.0,12.0,111228.70,0
2984,ACC102984,8156442036,Mani,Current,793780.0,86084,47663,496156.0,14,unknown,...,2015-03-13,927527.0,496156.0,1,4042,Low Balance,2022.0,12.0,69461.84,0

In [ ]:
df.isnull().sum()

Account_Id           0
Account_Number       0
Name                 0
Account_Type         0
Balance              0
Fixed_Deposit        0
Recurring_Deposit    0
Loan_Amount          0
Interest_Rate        0
Branch               0
City                 0
Country              0
Email                0
Phone_Number         0
Transaction_Type     0
Withdrawal           0
Deposit              0
Transaction_Date     0
Account_Open_Date    0
Total_Balance        0
Loan_Status          0
Loan_Staus           0
Customer_Tenure      0
Account_Category     0
Year                 0
Month                0
Interest_Per_Year    0
Zero_Balance_Flag    0
dtype: int64

In [ ]:
print(df.to_string())

     Account_Id  Account_Number    Name Account_Type    Balance  Fixed_Deposit  Recurring_Deposit  Loan_Amount  Interest_Rate     Branch      City        Country             Email  Phone_Number Transaction_Type  Withdrawal  Deposit Transaction_Date Account_Open_Date  Total_Balance  Loan_Status Loan_Staus  Customer_Tenure Account_Category    Year  Month  Interest_Per_Year Zero_Balance_Flag
0     ACC100000      9839401802   Divya           FD  1642743.0          60263              16023     100268.0             10      Delhi    Mumbai            UAE   divya@gmail.com    0000000000           Credit      157892     4886       2024-07-17        2022-10-24      1719029.0     100268.0          1             1260      Low Balance  2024.0    7.0           10026.80                 0
1     ACC100001      7548779029   Aisha      Current  2417439.0          25658              18942     781743.0             12  Hyderabad  New York  Unites States   aisha@gmail.com  2638242648.0            DEBIT       53355   185796       2021-01-09        2016-08-23      2462039.0     781743.0          1             3513   Median Balance  2021.0    1.0           93809.16                 0
3     ACC100003      9970006983  Robert      Savings  2249435.0          89789              24276     186769.0             14    Chennai   Unknown  Unites States  robert@gmail.com  4798808687.0              DBT      -12935   173165       2022-05-19        2019-04-02      2363500.0     186769.0          1             2561   Median Balance  2022.0    5.0           26147.66                 0
5     ACC100005      5404141609    John           RD  4328368.0          50015              41523     204020.0             10      Delhi   Unknown          India    john@gmail.com  4663625198.0           Credit       48806    87982       2017-03-06        2017-11-17      4419906.0     204020.0          1             3062     High Balance  2017.0    3.0           20402.00                 0
6     ACC100006      5819331062    Kavi      Savings  4344539.0          23776              30080      15939.0             16      Delhi    Mumbai          India    kavi@gmail.com  3826578402.0           credit      129997   124013       2016-10-25        2020-06-21      4398395.0      15939.0          1             2115     High Balance  2016.0   10.0            2550.24                 0
9     ACC100009      1487365080   Kumar      Current   693974.0          60713              30306     877121.0              8     Mumbai     Delhi          India   kumar@gmail.com  8301044688.0           credit      -38889   -12496       2022-11-03        2021-05-03       784993.0     877121.0          1             1799      Low Balance  2022.0   11.0           70169.68                 0
11    ACC100011      6692548372   Divya           RD  4925778.0          46214              33986     444351.0             12  Hyderabad     Dubai            UAE   divya@gmail.com  2565552571.0           Credit         108    62296       2021-05-20        2023-05-01      5005978.0     444351.0          1             1071     High Balance  2021.0    5.0           53322.12                 0
12    ACC100012      1187276799    Kavi      Savings  1368175.0          43484              17453    1699536.0             16      Delhi    Mumbai  Unites States    kavi@gmail.com  8470420346.0              DBT      175732    43179       2024-04-17        2015-05-08      1429112.0    1699536.0          1             3986      Low Balance  2024.0    4.0          271925.76                 0
13    ACC100013      5712337175    John           FD   639944.0          18070              35777     678105.0              8     Mumbai     Dubai        unknown    john@gmail.com  9070856969.0           Credit      104165   147177       2017-07-09        2021-09-21       693791.0     678105.0          1             1658      Low Balance  2017.0    7.0           54248.40                 0
15    ACC100015      4555670279  Fatima      Current  1388533.0          87142              21699     174078.0             10  Hyderabad     Dubai        unknown  fatima@gmail.com  2673192072.0            DEBIT       45285    96410       2020-05-28        2018-01-10      1497374.0     174078.0          1             3008      Low Balance  2020.0    5.0           17407.80                 0
16    ACC100016      1744293433    Arun      Savings  3127945.0          46175               7805          0.0              8      Delhi   Unknown  Unites States    arun@gmail.com  4064562924.0           Credit      -44051   133062       2024-03-10        2018-05-28      3181925.0          0.0          0             2870     High Balance  2024.0    3.0               0.00                 0
19    ACC100019      7996256236   Aisha      Unknown  2417439.0          33496              23548     490328.0             12     Mumbai   Chennai          India  noemail@bank.com  8720231067.0           credit      -29642   -46733       2015-06-02        2024-02-06      2474483.0     490328.0          1              790   Median Balance  2015.0    6.0           58839.36                 0
21    ACC100021      9947638415    Mani           FD  4048502.0          89112              31667    1097739.0             10    unknown   Chennai          India    mani@gmail.com  6864996942.0           credit      163709     1934       2015-08-23        2022-05-29      4169281.0    1097739.0          1             1408     High Balance  2015.0    8.0          109773.90                 0
22    ACC100022      4601247461    John      Current  1726203.0          39081              27569     169208.0             16    unknown     Dubai          India    john@gmail.com  4527053068.0           credit      104697   163945       2020-01-02        2023-08-08      1792853.0     169208.0          1              972      Low Balance  2020.0    1.0           27073.28                 0
23    ACC100023      9187729753    John      Savings  4889003.0          86188               4748       9870.0             16  Bangalore     Dubai  Unites States    john@gmail.com  3786028087.0           Credit      115650   153196       2018-02-14        2015-05-14      4979939.0       9870.0          1             3980     High Balance  2018.0    2.0            1579.20                 0
25    ACC100025      4930987466    John      Current  2548260.0          21447              24933     624421.0             10    unknown   Unknown  Unites States  noemail@bank.com  7939791483.0            DEBIT       56357   149938       2021-12-24        2023-03-26      2594640.0     624421.0          1             1107     High Balance  2021.0   12.0           62442.10                 0
26    ACC100026      1572025740   Divya      Savings  3987776.0           5713              49407    1994168.0             12      Delhi   Unknown        unknown   divya@gmail.com  9714670501.0           Credit       28752     5284       2021-02-02        2019-12-08      4042896.0    1994168.0          1             2311     High Balance  2021.0    2.0          239300.16                 0
29    ACC100029      3746036109    John      Current  4842472.0          81317              13051     471680.0             10  Bangalore   Chennai          India    john@gmail.com  1213850769.0              DBT      134943   -30802       2020-12-20        2017-03-07      4936840.0     471680.0          1             3317     High Balance  2020.0   12.0           47168.00                 0
30    ACC100030      7961307397    Mani           FD  2480179.0          36586              12015    1546617.0              8  Bangalore   Chennai  Unites States    mani@gmail.com  6657373782.0           Credit        5479   166464       2016-10-28        2015-03-04      2528780.0    1546617.0          1             4051     High Balance  2016.0   10.0          123729.36                 0
32    ACC100032      3565289826    Mani           FD  2231020.0          82558                 55     649792.0             12    Chennai     Delhi        unknown    mani@gmail.com  6719726261.0              DBT       45257    14291       2022-08-18        2020-03-21      2313633.0     649792.0          1             2207   Median Balance  2022.0    8.0           77975.04                 0
34    ACC100034      7904397119   Divya      Current  2643714.0          17260              47045    1513241.0              8  Hyderabad   Chennai            UAE   divya@gmail.com  5455637686.0            debit       50776   141076       2022-03-02        2017-11-29      2708019.0    1513241.0          1             3050     High Balance  2022.0    3.0          121059.28                 0
35    ACC100035      6402651504    Arun      Current  4939847.0          53441                846     945614.0             10  Bangalore   Unknown          India    arun@gmail.com  4595323030.0            DEBIT      -33611    72177       2020-10-08        2020-07-11      4994134.0     945614.0          1             2095     High Balance  2020.0   10.0           94561.40                 0
37    ACC100037      4139051895   Divya           FD  4752116.0          73698               5415     217645.0             10    Chennai     Dubai          India   divya@gmail.com    0000000000           Credit      -37781   -49765       2017-05-22        2018-06-06      4831229.0     217645.0          1             2861     High Balance  2017.0    5.0           21764.50                 0
38    ACC100038      7541516185   Divya           FD  1906109.0          82985              18520     938027.0             10    unknown   Chennai          India   divya@gmail.com  7250608006.0           Credit       38861    36740       2017-03-31        2020-11-21      2007614.0     938027.0          1             1962      Low Balance  2017.0    3.0           93802.70                 0
39    ACC100039      3127828256  Fatima      Unknown  1577781.0          98723              10789    1262386.0             10    Chennai     Dubai            UAE  fatima@gmail.com  6035194905.0            debit       46646    33122       2023-11-05        2017-03-25      1687293.0    1262386.0          1             3299      Low Balance  2023.0   11.0          126238.60                 0
43    ACC100043      5440477172    Mani      Savings  1531530.0          94270               4757     834193.0              8  Hyderabad   Chennai            UAE    mani@gmail.com   603803557.0           credit      -13632    87855       2019-11-28        2019-10-26      1630557.0     834193.0          1             2354      Low Balance  2019.0   11.0           66735.44                 0
44    ACC100044      3684251440   Aisha           FD  2828604.0          93607              23570          0.0              8  Hyderabad   Unknown            UAE  noemail@bank.com  1150152307.0           Credit       42374    83554       2017-10-03        2017-02-16      2945781.0          0.0          0             3336     High Balance  2017.0   10.0               0.00                 0
46    ACC100046      5662223622  Fatima      Savings   561213.0          20079              36220     758734.0             14     Mumbai   Unknown          India  fatima@gmail.com  1104391266.0            debit       16358    98399       2021-04-27        2017-03-15       617512.0     758734.0          1             3309      Low Balance  2021.0    4.0          106222.76                 0
48    ACC100048      1078987338   Aisha      Current    66739.0          92201              38243    1880969.0             14    unknown  New York        unknown   aisha@gmail.com    0000000000            debit      188009   157980       2023-04-05        2018-02-11       197183.0    1880969.0          1             2976      Low Balance  2023.0    4.0          263335.66                 0
49    ACC100049      7874167563    Arun           FD  4717348.0          93065              11664    1079385.0             10      Delhi   Unknown          India    arun@gmail.com  9150243294.0            DEBIT      -33275   142468       2020-08-20        2024-10-23      4822077.0    1079385.0          1              530     High Balance  2020.0    8.0          107938.50                 0
51    ACC100051      9923934193   Kumar      Current  3825754.0          85469              20581     597847.0              8      Delhi     Dubai        unknown   kumar@gmail.com    98607274.0           Credit        5337    60616       2019-02-17        2021-08-18      3931804.0     597847.0          1             1692     High Balance  2019.0    2.0           47827.76                 0
53    ACC100053      9748881168   Kumar      Savings   788003.0          35435              30907    1326230.0             12     Mumbai   Unknown            UAE   kumar@gmail.com  7966670358.0              DBT      -30574   -12735       2023-11-07        2015-01-16       854345.0    1326230.0          1             4098      Low Balance  2023.0   11.0          159147.60                 0
60    ACC100060      8544693324    Mani      Savings  2417439.0          87263              30220     460452.0             12  Hyderabad   Chennai        unknown    mani@gmail.com   717252698.0           Credit      117581    -7466       2018-06-12        2016-07-25      2534922.0     460452.0          1             3542   Median Balance  2018.0    6.0           55254.24                 0
62    ACC100062      2647602123    Mani      Savings  2417439.0           7813              31598    1153950.0             14  Bangalore  New York            UAE    mani@gmail.com  9691130286.0              DBT      -25140   102267       2022-10-15        2021-01-13      2456850.0    1153950.0          1             1909   Median Balance  2022.0   10.0          161553.00                 0
65    ACC100065      1005290717    Mani      Current  3927019.0          79083              34531     961129.0             12    Chennai    Mumbai            UAE    mani@gmail.com  5544177074.0           Credit        2098    96323       2018-05-09        2015-04-12      4040633.0     961129.0          1             4012     High Balance  2018.0    5.0          115335.48                 0
66    ACC100066      4694197536  Fatima      Savings   338590.0          49930              32981    1755982.0             10    unknown  New York            UAE  fatima@gmail.com  8553097101.0            debit       56661   107215       2019-04-11        2020-05-03       421501.0    1755982.0          1             2164      Low Balance  2019.0    4.0          175598.20                 0
68    ACC100068      8805234489   Aisha      Savings  3943710.0          56446              21288    1587690.0             12    Chennai     Delhi        unknown  noemail@bank.com  1568292637.0              DBT       50734   107702       2021-06-14        2016-11-25      4021444.0    1587690.0          1             3419     High Balance  2021.0    6.0          190522.80                 0
70    ACC100070      2883838883   Priya           RD  3981419.0          77539              43585     291207.0             16      Delhi     Delhi        unknown  noemail@bank.com  6922952174.0            debit       64225    66400       2022-12-24        2017-03-04      4102543.0     291207.0          1             3320     High Balance  2022.0   12.0           46593.12                 0
71    ACC100071      7496632833   Divya           FD  4164279.0           4648              35133          0.0             14  Hyderabad     Dubai  Unites States   divya@gmail.com  7683165088.0           Credit      104351   159373       2023-11-09        2018-06-06      4204060.0          0.0          0             2861     High Balance  2023.0   11.0               0.00                 0
72    ACC100072      2018026902   Divya      Current  4121774.0          44738              33397     134832.0              8      Delhi  New York          India   divya@gmail.com  9804370853.0              DBT      102999    36475       2023-09-14        2020-05-10      4199909.0     134832.0          1             2157     High Balance  2023.0    9.0           10786.56                 0
74    ACC100074      9382967777    Kavi      Savings  3792323.0          15398               6638    1287076.0             14    Chennai     Delhi          India    kavi@gmail.com  5363196714.0           Credit      116129    82311       2019-05-12        2022-09-06      3814359.0    1287076.0          1             1308     High Balance  2019.0    5.0          180190.64                 0
77    ACC100077      2927124440   Priya      Current  1911977.0          96546              22443          0.0             12  Hyderabad   Unknown        unknown   priya@gmail.com  7918249715.0            DEBIT       50494    90180       2024-06-01        2018-03-23      2030966.0          0.0          0             2936      Low Balance  2024.0    6.0               0.00                 0
78    ACC100078      8379282417   Aisha           RD  2330932.0          24596              33174    1644753.0             14  Bangalore  New York          India  noemail@bank.com  4832345213.0           Credit        3551    92628       2024-12-14        2021-12-16      2388702.0    1644753.0          1             1572   Median Balance  2024.0   12.0          230265.42                 0
79    ACC100079      7012547073   Kumar      Savings  2738890.0          86365              34054    1736588.0             12    Chennai    Mumbai            UAE   kumar@gmail.com  6709973335.0           credit      153502    94539       2018-09-11        2018-04-10      2859309.0    1736588.0          1             2918     High Balance  2018.0    9.0          208390.56                 0
80    AC-100080      8813356661   Kumar           FD  1856039.0          52249              37384     556956.0             14     Mumbai   Unknown            UAE   kumar@gmail.com  8977094317.0            DEBIT       94745   157738       2023-07-29        2023-11-13      1945672.0     556956.0          1              875      Low Balance  2023.0    7.0           77973.84                 0
81    ACC100081      1721615534  Robert           FD  3971080.0          94880              17014    1366401.0             16  Bangalore   Unknown          India  robert@gmail.com  4269888126.0            debit      184386    31571       2019-04-27        2024-07-06      4082974.0    1366401.0          1              639     High Balance  2019.0    4.0          218624.16                 0
83    ACC100083      6286371115    John      Savings  4027716.0          98117               5249     639991.0             10     Mumbai    Mumbai          India    john@gmail.com   216375934.0           credit        6549   115575       2021-05-23        2024-03-28      4131082.0     639991.0          1              739     High Balance  2021.0    5.0           63999.10                 0
85    ACC100085      6762448108  Robert           FD  2417439.0          30682              47864    1057745.0             16     Mumbai    Mumbai            UAE  robert@gmail.com  3693165255.0           Credit       68413    97235       2015-01-09        2016-04-05      2495985.0    1057745.0          1             3653   Median Balance  2015.0    1.0          169239.20                 0
87    ACC100087      9152971599    Arun      Current  2897893.0          11138              35298    1068560.0             16      Delhi   Unknown        unknown    arun@gmail.com  4174138331.0              DBT       68947   154894       2021-10-30        2016-01-25      2944329.0    1068560.0          1             3724     High Balance  2021.0   10.0          170969.60                 0
89    ACC100089      8104201471    Mani           RD   910612.0          26715              27605     417387.0              8     Mumbai     Delhi  Unites States    mani@gmail.com  5461455496.0            debit      122851   149900       2018-12-17        2017-06-19       964932.0     417387.0          1             3213      Low Balance  2018.0   12.0           33390.96                 0